<section class="page-intro page-intro-actions">
  <div><p><?= tpl_escape(tpl_get($ctx, 'Subtitle')) ?></p></div>
  <div class="intro-actions inventory-intro-actions">
    <?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>
    <a class="button secondary" href="/inventory"><svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg>Kembali ke inventory aktif</a>
    <?php else: ?>
    <a class="button secondary history-button" href="/inventory?history=1"><svg viewBox="0 0 24 24"><path d="M3 12a9 9 0 1 0 3-6.7M3 4v5h5"/><path d="M12 7v5l3 2"/></svg>History</a>
    <?php if (tpl_truthy(tpl_get($ctx, 'CanCreateBTD'))): ?><button class="button primary inventory-entry-button" type="button" data-open-inventory-modal="BTD"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Pencatatan BTD</button><?php endif; ?>
    <?php if (tpl_truthy(tpl_get($ctx, 'CanCreateBDN'))): ?><button class="button primary inventory-entry-button" type="button" data-open-inventory-modal="BDN"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Penetapan BDN</button><?php endif; ?>
    <?php if (tpl_truthy(tpl_get($ctx, 'CanCreateTitipan'))): ?><button class="button primary inventory-entry-button" type="button" data-open-inventory-modal="TITIPAN"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Pemasukan barang titipan</button><?php endif; ?>
    <?php if (tpl_truthy(tpl_get($ctx, 'CanRunInventoryActions'))): ?><button class="button primary inventory-action-button" type="button" data-open-inventory-action><svg viewBox="0 0 24 24"><path d="M5 7h14M5 12h14M5 17h14"/></svg>Action</button><?php endif; ?>
    <?php endif; ?>
  </div>
</section>

<section class="inventory-tabs" aria-label="Jenis inventory">
  <a class="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'InventoryType'), ''))): ?>active<?php endif; ?>" href="/inventory?<?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>history=1&<?php endif; ?>tpp=<?= tpl_escape(tpl_get($ctx, 'FacilityID')) ?>&q=<?= tpl_escape(tpl_get($ctx, 'Query')) ?>">Semua <span><?= tpl_escape(tpl_get($ctx, 'Pagination.TotalItems')) ?></span></a>
  <?php if (tpl_truthy(tpl_can(tpl_get($ctx, 'User'), 'inventory.type.btd'))): ?><a class="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'InventoryType'), 'BTD'))): ?>active<?php endif; ?>" href="/inventory?<?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>history=1&<?php endif; ?>type=btd&tpp=<?= tpl_escape(tpl_get($ctx, 'FacilityID')) ?>&q=<?= tpl_escape(tpl_get($ctx, 'Query')) ?>">BTD</a><?php endif; ?>
  <?php if (tpl_truthy(tpl_can(tpl_get($ctx, 'User'), 'inventory.type.bdn'))): ?><a class="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'InventoryType'), 'BDN'))): ?>active<?php endif; ?>" href="/inventory?<?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>history=1&<?php endif; ?>type=bdn&tpp=<?= tpl_escape(tpl_get($ctx, 'FacilityID')) ?>&q=<?= tpl_escape(tpl_get($ctx, 'Query')) ?>">BDN</a><?php endif; ?>
  <?php if (tpl_truthy(tpl_can(tpl_get($ctx, 'User'), 'inventory.type.bmmn'))): ?><a class="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'InventoryType'), 'BMMN'))): ?>active<?php endif; ?>" href="/inventory?<?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>history=1&<?php endif; ?>type=bmmn&tpp=<?= tpl_escape(tpl_get($ctx, 'FacilityID')) ?>&q=<?= tpl_escape(tpl_get($ctx, 'Query')) ?>">BMMN</a><?php endif; ?>
  <?php if (tpl_truthy(tpl_can(tpl_get($ctx, 'User'), 'inventory.type.titipan'))): ?><a class="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'InventoryType'), 'TITIPAN'))): ?>active<?php endif; ?>" href="/inventory?<?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>history=1&<?php endif; ?>type=titipan&tpp=<?= tpl_escape(tpl_get($ctx, 'FacilityID')) ?>&q=<?= tpl_escape(tpl_get($ctx, 'Query')) ?>">Barang Titipan</a><?php endif; ?>
</section>

<section class="panel table-panel">
  <form class="table-toolbar" method="get" action="/inventory">
    <?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?><input type="hidden" name="history" value="1"><?php endif; ?>
    <input type="hidden" name="type" value="<?= tpl_escape(tpl_lower(tpl_get($ctx, 'InventoryType'))) ?>">
    <input type="hidden" name="page_size" value="<?= tpl_escape(tpl_get($ctx, 'Pagination.PageSize')) ?>">
    <label class="search-field"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" name="q" value="<?= tpl_escape(tpl_get($ctx, 'Query')) ?>" placeholder="Cari nomor penetapan, kontainer, uraian, atau pemilik…"><kbd>/</kbd></label>
    <label class="select-field"><span>TPP</span><select name="tpp" data-auto-submit><option value="">Semua TPP</option><?php $__range1 = tpl_iter(tpl_get($ctx, 'Facilities')); if (count($__range1) > 0): $__parent1 = $ctx; foreach ($__range1 as $__key1 => $__item1): $ctx = $__item1; ?><option value="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>" <?php if (tpl_truthy(tpl_eq(tpl_get($root, 'FacilityID'), tpl_get($ctx, 'ID')))): ?>selected<?php endif; ?>><?= tpl_escape(tpl_get($ctx, 'Name')) ?></option><?php $ctx = $__parent1; endforeach; endif; ?></select></label>
    <label class="select-field"><span>Status</span><select name="status" data-auto-submit><option value="">Semua status</option><option value="masih_di_tps" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'masih_di_tps'))): ?>selected<?php endif; ?>>Masih di TPS</option><option value="ditetapkan" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'ditetapkan'))): ?>selected<?php endif; ?>>Baru ditetapkan</option><option value="pemindahan" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'pemindahan'))): ?>selected<?php endif; ?>>Pemindahan</option><option value="pencacahan" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'pencacahan'))): ?>selected<?php endif; ?>>Pencacahan</option><option value="request_penelitian_pfpd" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'request_penelitian_pfpd'))): ?>selected<?php endif; ?>>Request PFPD</option><option value="penelitian_pfpd" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'penelitian_pfpd'))): ?>selected<?php endif; ?>>Penelitian PFPD</option><option value="bmmn_aktif" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'bmmn_aktif'))): ?>selected<?php endif; ?>>BMMN aktif</option><option value="usulan_peruntukan_bmmn" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'usulan_peruntukan_bmmn'))): ?>selected<?php endif; ?>>Usulan peruntukan</option><option value="persetujuan_peruntukan_bmmn" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Status'), 'persetujuan_peruntukan_bmmn'))): ?>selected<?php endif; ?>>Persetujuan peruntukan</option></select></label>
    <label class="select-field sort-field"><span>Urutkan</span><select name="sort" data-auto-submit><option value="newest" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'newest'))): ?>selected<?php endif; ?>>Pembaruan terbaru</option><option value="determination_newest" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'determination_newest'))): ?>selected<?php endif; ?>>Penetapan terbaru</option><option value="oldest" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'oldest'))): ?>selected<?php endif; ?>>Penetapan terlama</option><option value="value_desc" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'value_desc'))): ?>selected<?php endif; ?>>Nilai tertinggi</option><option value="value_asc" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'value_asc'))): ?>selected<?php endif; ?>>Nilai terendah</option><option value="container_asc" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'container_asc'))): ?>selected<?php endif; ?>>Kontainer A–Z</option><option value="container_desc" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'container_desc'))): ?>selected<?php endif; ?>>Kontainer Z–A</option><option value="tpp" <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Sort'), 'tpp'))): ?>selected<?php endif; ?>>Nama TPP</option></select></label>
    <button class="button compact filter-button" type="submit">Terapkan</button>
  </form>

  <div class="table-meta"><p>Menampilkan <strong><?= tpl_escape(tpl_get($ctx, 'Pagination.StartItem')) ?>–<?= tpl_escape(tpl_get($ctx, 'Pagination.EndItem')) ?></strong> dari <?= tpl_escape(tpl_get($ctx, 'Pagination.TotalItems')) ?> <?php if (tpl_truthy(tpl_get($ctx, 'History'))): ?>barang dalam riwayat<?php else: ?>barang aktif<?php endif; ?></p><span><i class="legend-dot green"></i>Nomor penetapan membuka detail; status kanan membuka timestamp</span></div>
  <div class="table-scroll-top" data-table-scroll-top aria-label="Geser tabel ke samping"><div></div></div>
  <div class="table-pagination">
    <div class="page-size-picker"><span>Tampilkan</span><?php $__range2 = tpl_iter(tpl_get($ctx, 'Pagination.Sizes')); if (count($__range2) > 0): $__parent2 = $ctx; foreach ($__range2 as $__key2 => $__item2): $ctx = $__item2; ?><a class="<?php if (tpl_truthy(tpl_get($ctx, 'Selected'))): ?>active<?php endif; ?>" href="<?= tpl_escape(tpl_get($ctx, 'URL')) ?>"><?= tpl_escape(tpl_get($ctx, 'Value')) ?></a><?php $ctx = $__parent2; endforeach; endif; ?><span>baris</span></div>
    <div class="page-navigation"><span>Halaman <?= tpl_escape(tpl_get($ctx, 'Pagination.Page')) ?> dari <?= tpl_escape(tpl_get($ctx, 'Pagination.TotalPages')) ?> · Total <?= tpl_escape(tpl_get($ctx, 'Pagination.TotalItems')) ?> item</span><?php if (tpl_truthy(tpl_get($ctx, 'Pagination.HasPrevious'))): ?><a href="<?= tpl_escape(tpl_get($ctx, 'Pagination.PreviousURL')) ?>">Sebelumnya</a><?php else: ?><span class="disabled">Sebelumnya</span><?php endif; ?><?php if (tpl_truthy(tpl_get($ctx, 'Pagination.HasNext'))): ?><a href="<?= tpl_escape(tpl_get($ctx, 'Pagination.NextURL')) ?>">Berikutnya</a><?php else: ?><span class="disabled">Berikutnya</span><?php endif; ?></div>
  </div>
  <div class="table-wrap" data-table-scroll-body>
    <table class="data-table inventory-table">
      <thead><tr><th>Jenis</th><th>Nomor penetapan</th><th>Kontainer / manifest</th><th>Uraian & jenis barang</th><th>Jumlah</th><th>Nilai barang</th><th>Status lokasi</th><th>Umur</th><th class="status-column">Status barang</th><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'User.Role'), 'admin'))): ?><th class="admin-action-column">Admin</th><?php endif; ?></tr></thead>
      <tbody>
      <?php $__range3 = tpl_iter(tpl_get($ctx, 'Items')); if (count($__range3) > 0): $__parent3 = $ctx; foreach ($__range3 as $__key3 => $__item3): $ctx = $__item3; ?>
        <tr>
          <td><span class="type-pill <?= tpl_escape(tpl_lower(tpl_get($ctx, 'Type'))) ?>"><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Type'), 'TITIPAN'))): ?>Barang Titipan<?php else: ?><?= tpl_escape(tpl_get($ctx, 'Type')) ?><?php endif; ?></span><small><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Type'), 'TITIPAN'))): ?><?= tpl_escape(tpl_get($ctx, 'EntrustedCategory')) ?><?php if (tpl_truthy(tpl_get($ctx, 'SourceOffice'))): ?> · <?= tpl_escape(tpl_get($ctx, 'SourceOffice')) ?><?php endif; ?><?php else: ?>Asal <?= tpl_escape(tpl_get($ctx, 'OriginType')) ?><?php endif; ?></small></td>
          <td><button class="reference-button" type="button" data-detail-url="/api/inventory/<?= tpl_escape(tpl_get($ctx, 'ID')) ?>"><strong><?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?></strong><small><?= tpl_escape(tpl_date(tpl_get($ctx, 'DeterminationDate'))) ?></small></button></td>
          <td><?php if (tpl_truthy(tpl_get($ctx, 'ContainerNo'))): ?><strong><?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?></strong><small>Ukuran <?= tpl_escape(tpl_container_size_label(tpl_get($ctx, 'ContainerSize'))) ?> · <?= tpl_escape(tpl_get($ctx, 'ManifestNo')) ?> · Pos <?= tpl_escape(tpl_get($ctx, 'ManifestPosition')) ?></small><?php else: ?><strong>LCL · <?= tpl_escape(tpl_number(tpl_get($ctx, 'EstimatedVolumeM3'))) ?> m³</strong><small><?= tpl_escape(tpl_get($ctx, 'ManifestNo')) ?> · Pos <?= tpl_escape(tpl_get($ctx, 'ManifestPosition')) ?></small><?php endif; ?></td>
          <td class="description-cell"><strong><?= tpl_escape(tpl_get($ctx, 'Description')) ?></strong><small><?php if (tpl_truthy(tpl_get($ctx, 'ItemKind'))): ?><?= tpl_escape(tpl_get($ctx, 'ItemKind')) ?><?php else: ?>Jenis belum dirinci<?php endif; ?><?php if (tpl_truthy(tpl_get($ctx, 'GoodsCondition'))): ?> · Kondisi <?= tpl_escape(tpl_get($ctx, 'GoodsCondition')) ?><?php endif; ?></small></td>
          <td><strong><?= tpl_escape(tpl_number(tpl_get($ctx, 'Quantity'))) ?></strong><small><?= tpl_escape(tpl_get($ctx, 'Unit')) ?></small></td>
          <td><strong><?= tpl_escape(tpl_rupiah(tpl_get($ctx, 'GoodsValue'))) ?></strong><small>Nilai penelitian</small></td>
          <td><span class="location-pill <?php if (tpl_truthy(tpl_get($ctx, 'AtTPP'))): ?>at-tpp<?php else: ?>at-tps<?php endif; ?>"><?= tpl_escape(tpl_get($ctx, 'LocationStatus')) ?></span><small><?= tpl_escape(tpl_get($ctx, 'Location')) ?></small></td>
          <td><span class="age-pill <?php if (tpl_truthy(tpl_ge(tpl_age($ctx, tpl_get($root, 'Now')), 45))): ?>danger<?php elseif (tpl_truthy(tpl_ge(tpl_age($ctx, tpl_get($root, 'Now')), 30))): ?>warning<?php endif; ?>"><?= tpl_escape(tpl_age($ctx, tpl_get($root, 'Now'))) ?> hari</span></td>
          <td class="status-column"><button class="status-button <?= tpl_escape(tpl_status_tone(tpl_get($ctx, 'StatusCode'))) ?>" type="button" data-timeline-url="/api/inventory/<?= tpl_escape(tpl_get($ctx, 'ID')) ?>/timeline"><span><?= tpl_escape(tpl_get($ctx, 'StatusLabel')) ?></span><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></button><small>Diperbarui <?= tpl_escape(tpl_date(tpl_get($ctx, 'UpdatedAt'))) ?></small></td>
          <?php if (tpl_truthy(tpl_eq(tpl_get($root, 'User.Role'), 'admin'))): ?><td class="admin-action-column"><form method="post" action="/admin/inventory/<?= tpl_escape(tpl_get($ctx, 'ID')) ?>/delete" data-delete-inventory-form data-delete-reference="<?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?>"><input type="hidden" name="_csrf" value="<?= tpl_escape(tpl_get($root, 'CSRF')) ?>"><input type="hidden" name="return_to" value="<?php if (tpl_truthy(tpl_get($root, 'History'))): ?>/inventory?history=1<?php else: ?>/inventory<?php endif; ?>"><button class="delete-inventory-button" type="submit" title="Hapus data barang secara permanen"><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 11v6M14 11v6"/></svg><span>Hapus</span></button></form></td><?php endif; ?>
        </tr>
<?php $ctx = $__parent3; endforeach; else: ?>
        <tr><td colspan="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'User.Role'), 'admin'))): ?>10<?php else: ?>9<?php endif; ?>"><div class="empty-state"><span><svg viewBox="0 0 24 24"><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5z"/><path d="m4 7.5 8 4.5 8-4.5"/></svg></span><h3>Inventory tidak ditemukan</h3><p>Ubah filter atau tambahkan pencatatan BTD, penetapan BDN maupun pemasukan barang titipan baru.</p></div></td></tr>
      <?php endif; ?>
      </tbody>
    </table>
  </div>
</section>

<?php if (tpl_truthy(tpl_not(tpl_get($ctx, 'History')))): ?>
<?php if (tpl_truthy(tpl_get($ctx, 'CanCreateInventory'))): ?>
<div class="modal" id="inventory-create-modal" role="dialog" aria-modal="true" aria-labelledby="inventory-modal-title" hidden>
  <div class="modal-backdrop" data-close-modal></div>
  <section class="modal-panel modal-panel-wide">
    <header class="modal-header"><div><p class="eyebrow">Input awal inventory</p><h2 id="inventory-modal-title">Pencatatan BTD</h2><p data-inventory-modal-description>Barang baru secara default dicatat masih berada di TPS.</p></div><button class="icon-button" type="button" data-close-modal aria-label="Tutup"><svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg></button></header>
    <div class="inventory-entry-mode" role="tablist" aria-label="Metode input inventory">
      <button class="active" type="button" role="tab" aria-selected="true" data-inventory-entry-mode="manual"><svg viewBox="0 0 24 24"><path d="M4 19h16M6 16l9-9 3 3-9 9H6z"/></svg><span><strong>Isi form</strong><small>Input satu dokumen secara manual</small></span></button>
      <button type="button" role="tab" aria-selected="false" data-inventory-entry-mode="excel"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16h16V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></svg><span><strong>Upload Excel</strong><small>Masukkan banyak barang sekaligus</small></span></button>
    </div>
    <form class="modal-form" method="post" action="/inventory" enctype="multipart/form-data" data-inventory-manual-form>
      <input type="hidden" name="_csrf" value="<?= tpl_escape(tpl_get($ctx, 'CSRF')) ?>"><input type="hidden" name="item_type" value="BTD" data-item-type-input>
      <fieldset><legend data-document-fieldset-title>Dokumen penetapan</legend><div class="form-grid cols-3"><label><span data-determination-no-label>Nomor penetapan</span> <em>*</em><input name="determination_no" placeholder="Nomor dokumen penetapan" required></label><label><span data-determination-date-label>Tanggal penetapan</span> <em>*</em><input type="date" name="determination_date" value="<?= tpl_escape(tpl_isodate(tpl_get($ctx, 'Now'))) ?>" required></label><label data-bdn-category hidden>Kategori BDN <em>*</em><select name="category" disabled><option value="">Pilih kategori BDN</option><?php $__range4 = tpl_iter(tpl_get($ctx, 'BDNCategoryNames')); if (count($__range4) > 0): $__parent4 = $ctx; foreach ($__range4 as $__key4 => $__item4): $ctx = $__item4; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent4; endforeach; endif; ?></select></label><label class="span-3 document-upload-field">Upload dokumen dasar <span class="optional-mark">Opsional</span><input type="file" name="document_file" accept="application/pdf,image/jpeg,image/png,image/webp,image/gif"><small>PDF atau gambar, maksimal 8 MB. File tersimpan pada jejak audit.</small></label></div><div class="form-grid cols-2" data-entrusted-fields hidden><label>Kategori barang <em>*</em><select name="entrusted_category" disabled><option value="">Pilih kategori barang</option><?php $__range5 = tpl_iter(tpl_get($ctx, 'EntrustedCategoryNames')); if (count($__range5) > 0): $__parent5 = $ctx; foreach ($__range5 as $__key5 => $__item5): $ctx = $__item5; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent5; endforeach; endif; ?></select></label><label>Kantor/unit penitip <em>*</em><input name="source_office" placeholder="Nama kantor atau unit asal" disabled></label></div></fieldset>
      <fieldset><legend data-manifest-fieldset-title>BL, manifest, muatan, dan TPS asal</legend>
        <div class="form-grid cols-3"><label data-bl-field>Nomor BL <em data-bl-required-mark>*</em><span class="optional-mark" data-bl-optional-mark hidden>Opsional</span><input name="bl_no" data-bl-input maxlength="120" required></label><label data-bl-date-field>Tanggal BL <em data-bl-date-required-mark>*</em><span class="optional-mark" data-bl-date-optional-mark hidden>Opsional</span><input type="date" name="bl_date" data-bl-date-input required></label><label>Nomor manifest<input name="manifest_no" placeholder="BC 1.1-______"></label><label>Tanggal manifest<input type="date" name="manifest_date"></label><label>Pos manifest<input name="manifest_position" placeholder="0000"></label><label>Jenis muatan <em>*</em><select name="load_type" required data-load-type-select><option value="">Pilih jenis muatan</option><?php $__range6 = tpl_iter(tpl_get($ctx, 'LoadTypeOptions')); if (count($__range6) > 0): $__parent6 = $ctx; foreach ($__range6 as $__key6 => $__item6): $ctx = $__item6; ?><option value="<?= tpl_escape(tpl_get($ctx, 'Code')) ?>"><?= tpl_escape(tpl_get($ctx, 'Label')) ?></option><?php $ctx = $__parent6; endforeach; endif; ?></select></label><label class="span-2" data-origin-tps-field>TPS asal <em>*</em><select name="origin_warehouse" required><option value="">Pilih TPS asal</option><?php $__range7 = tpl_iter(tpl_get($ctx, 'TPSNames')); if (count($__range7) > 0): $__parent7 = $ctx; foreach ($__range7 as $__key7 => $__item7): $ctx = $__item7; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent7; endforeach; endif; ?></select></label></div>
        <section class="container-entry-section" data-fcl-container-section hidden>
          <div class="container-entry-heading"><div><h3>Kontainer dan identitas barang <em>*</em></h3><p>Tambahkan kontainer, lalu isi satu atau beberapa identitas barang di dalam kontainer tersebut. Setiap identitas menjadi satu baris inventory, tetapi kapasitas YOR tetap menghitung satu kontainer.</p></div><strong data-container-count>0 kontainer</strong></div>
          <div class="container-entry-composer"><label class="container-draft-field">Ukuran peti kemas<select data-container-size-draft><option value="">Pilih ukuran</option><?php $__range8 = tpl_iter(tpl_get($ctx, 'ContainerSizeOptions')); if (count($__range8) > 0): $__parent8 = $ctx; foreach ($__range8 as $__key8 => $__item8): $ctx = $__item8; ?><option value="<?= tpl_escape(tpl_get($ctx, 'Code')) ?>"><?= tpl_escape(tpl_get($ctx, 'Label')) ?></option><?php $ctx = $__parent8; endforeach; endif; ?></select></label><label class="container-draft-field">Nomor kontainer<input data-container-number-draft placeholder="ABCD 123456-7" autocomplete="off"></label><button class="button secondary compact" type="button" data-add-container>Tambah kontainer</button></div>
          <input type="hidden" name="containers_json" value="[]" data-containers-json disabled>
          <div class="initial-container-list" data-container-card-list><p class="container-list-empty">Belum ada kontainer. Tambahkan kontainer pertama untuk mulai mengisi identitas barang.</p></div>
        </section>
        <section class="lcl-volume-section" data-lcl-volume-section hidden>
          <label class="lcl-volume-field">Perkiraan volume barang <em>*</em><input type="number" min="0.01" step="0.01" name="estimated_volume_m3" data-lcl-volume-input disabled placeholder="Contoh: 18.5"><small class="field-inline-help">Satuan meter kubik (m³); digunakan untuk perhitungan SOR.</small></label>
          <div class="initial-goods-editor"><div class="container-entry-heading"><div><h3>Identitas barang LCL <em>*</em></h3><p>Tambahkan seluruh uraian barang dalam satu pengiriman LCL. Setiap identitas akan tampil sebagai satu baris inventory.</p></div><strong data-lcl-goods-count>0 barang</strong></div><input type="hidden" name="lcl_goods_json" value="[]" data-lcl-goods-json disabled><div data-lcl-goods-lines></div><button class="button secondary compact" type="button" data-add-lcl-goods-line>+ Tambah identitas barang</button></div>
        </section>
        <template data-initial-goods-line-template><section class="initial-goods-line" data-initial-goods-line><header><strong data-goods-line-title>Identitas barang</strong><button type="button" class="remove-line-button" data-remove-goods-line>Hapus</button></header><div class="form-grid cols-2"><label class="span-2">Uraian barang <em>*</em><textarea rows="2" data-goods-field="description" placeholder="Uraian barang dari dokumen dasar"></textarea></label><label>Jenis barang <em>*</em><select data-goods-field="item_kind"><option value="">Pilih jenis barang</option><?php $__range9 = tpl_iter(tpl_get($ctx, 'ItemKindNames')); if (count($__range9) > 0): $__parent9 = $ctx; foreach ($__range9 as $__key9 => $__item9): $ctx = $__item9; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent9; endforeach; endif; ?></select></label><label>Nilai awal barang<input inputmode="numeric" data-goods-field="goods_value" placeholder="Contoh: 250000000"></label><label>Jumlah <em>*</em><input type="number" step="0.01" min="0.01" data-goods-field="quantity" placeholder="0"></label><label>Satuan <em>*</em><select data-goods-field="unit"><option value="">Pilih satuan</option><?php $__range10 = tpl_iter(tpl_get($ctx, 'UnitNames')); if (count($__range10) > 0): $__parent10 = $ctx; foreach ($__range10 as $__key10 => $__item10): $ctx = $__item10; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent10; endforeach; endif; ?></select></label></div></section></template>
      </fieldset>
      <fieldset><legend>Status lokasi saat pencatatan/penetapan</legend><div class="location-choice"><p>Apakah barang sudah berada di TPP?</p><label><input type="radio" name="at_tpp" value="belum" checked data-at-tpp-choice> Belum — status “Masih di TPS”</label><label><input type="radio" name="at_tpp" value="sudah" data-at-tpp-choice> Sudah berada di TPP</label></div><div class="form-grid cols-2 conditional-location" data-tpp-location-fields hidden><label>TPP lokasi barang <em>*</em><select name="facility_id" data-tpp-select disabled><option value="">Pilih TPP</option><?php $__range11 = tpl_iter(tpl_get($ctx, 'Facilities')); if (count($__range11) > 0): $__parent11 = $ctx; foreach ($__range11 as $__key11 => $__item11): $ctx = $__item11; ?><option value="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>"><?= tpl_escape(tpl_get($ctx, 'Name')) ?></option><?php $ctx = $__parent11; endforeach; endif; ?></select></label><label>Blok / gudang di TPP<input name="location" data-tpp-location disabled placeholder="Opsional"></label></div></fieldset>
      <fieldset><legend>Pemilik barang</legend><div class="form-grid cols-2"><label>Nama shipper / consignee<input name="owner_name" placeholder="Nama perusahaan"></label><label class="span-2">Alamat shipper / consignee<textarea name="owner_address" rows="2" placeholder="Alamat lengkap"></textarea></label></div></fieldset>
      <footer class="modal-footer"><button class="button ghost" type="button" data-close-modal>Batal</button><button class="button primary" type="submit" data-inventory-create-submit>Simpan penetapan</button></footer>
    </form>
    <form class="modal-form inventory-import-form" method="post" action="/inventory/import" enctype="multipart/form-data" data-inventory-import-form hidden>
      <input type="hidden" name="_csrf" value="<?= tpl_escape(tpl_get($ctx, 'CSRF')) ?>"><input type="hidden" name="item_type" value="BTD" data-item-type-input>
      <section class="inventory-import-card">
        <div class="inventory-import-copy"><span class="import-icon"><svg viewBox="0 0 24 24"><path d="M12 16V4M7 9l5-5 5 5M5 20h14"/></svg></span><div><p class="eyebrow">Upload massal</p><h3 data-import-title>Upload banyak Pencatatan BTD</h3><p>Gunakan template resmi sesuai jenis pemasukan. Setiap baris yang valid akan disimpan sebagai satu baris inventory.</p></div></div>
        <div class="inventory-template-box"><div><strong>1. Unduh template Excel</strong><p>Template sudah berisi kolom wajib, dropdown referensi, petunjuk, dan contoh isian pada baris kedua.</p></div><a class="button secondary" href="/templates/template_upload_btd.xlsx?v=1.0.8" download data-import-template-link><svg viewBox="0 0 24 24"><path d="M12 3v12M7 10l5 5 5-5M5 21h14"/></svg>Unduh template BTD</a></div>
        <label class="inventory-file-drop"><input type="file" name="excel_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required data-inventory-excel-file><span class="file-drop-icon"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16h16V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></svg></span><span><strong>2. Pilih file Excel yang sudah diisi</strong><small data-inventory-file-name>Belum ada file dipilih · format .xlsx · maksimal 1.000 baris / 6 MB</small></span><em>Pilih file</em></label>
        <aside class="inventory-import-note"><strong>Sebelum menyimpan</strong><p>Hapus atau timpa contoh pada baris kedua. Satu baris mewakili satu identitas barang. Nomor kontainer FCL boleh diulang untuk beberapa barang dalam kontainer yang sama selama data dokumen dan kontainernya konsisten.</p></aside>
      </section>
      <footer class="modal-footer"><button class="button ghost" type="button" data-close-modal>Batal</button><button class="button primary" type="submit" data-inventory-import-submit>Upload dan simpan ke inventory</button></footer>
    </form>
  </section>
</div>
<?php endif; ?>

<?php if (tpl_truthy(tpl_get($ctx, 'CanRunInventoryActions'))): ?>
<div class="modal action-modal" id="inventory-action-drawer" role="dialog" aria-modal="true" aria-labelledby="inventory-action-title" hidden>
  <div class="modal-backdrop" data-close-modal></div>
  <section class="modal-panel modal-panel-wide action-modal-panel">
    <header class="modal-header"><div><p class="eyebrow">Action inventory</p><h2 id="inventory-action-title" data-action-modal-title data-default-title="Pilih submenu action inventory">Pilih submenu action inventory</h2><p data-action-modal-description data-default-description="Pilih action yang ingin dikerjakan. Form lengkap akan terbuka setelah submenu dipilih.">Pilih action yang ingin dikerjakan. Form lengkap akan terbuka setelah submenu dipilih.</p></div><button class="icon-button" type="button" data-close-modal aria-label="Tutup"><svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg></button></header>
    <form method="post" action="/inventory/bulk-event" enctype="multipart/form-data" data-inventory-action-form>
      <input type="hidden" name="_csrf" value="<?= tpl_escape(tpl_get($ctx, 'CSRF')) ?>"><input type="hidden" name="event_code" data-event-code>
      <div class="action-modal-scroll">
        <section class="action-menu-stage" data-action-menu>
          <div class="action-menu-intro"><strong>Pilih jenis action</strong><p>Klik salah satu submenu di bawah. Setelah dipilih, sistem menampilkan form action dalam popup yang lebih lebar dan mudah dikerjakan.</p></div>
          <div class="step-picker action-step-grid">
            <?php $__range12 = tpl_iter(tpl_get($ctx, 'InventoryActions')); if (count($__range12) > 0): $__parent12 = $ctx; foreach ($__range12 as $__key12 => $__item12): $ctx = $__item12; ?><button type="button" class="step-option <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Code'), 'penetapan_bmmn'))): ?>highlight<?php endif; ?> <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'Code'), 'pengeluaran_barang'))): ?>final-step<?php endif; ?>" data-step-code="<?= tpl_escape(tpl_get($ctx, 'Code')) ?>" data-step-label="<?= tpl_escape(tpl_get($ctx, 'Label')) ?>" data-step-description="<?= tpl_escape(tpl_get($ctx, 'Description')) ?>" data-step-document="<?= tpl_escape(tpl_get($ctx, 'Document')) ?>" data-bmmn-only="<?= tpl_escape(tpl_get($ctx, 'BMMNOnly')) ?>" data-non-bmmn-only="<?= tpl_escape(tpl_get($ctx, 'NonBMMNOnly')) ?>"><span class="step-check"><svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg></span><span><strong><?= tpl_escape(tpl_get($ctx, 'Label')) ?></strong><small><?= tpl_escape(tpl_get($ctx, 'Description')) ?></small></span><svg class="step-arrow" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></button><?php $ctx = $__parent12; endforeach; endif; ?>
          </div>
        </section>
        <section class="action-detail-stage" data-action-detail hidden>
          <div class="action-detail-toolbar"><button class="button ghost compact action-back-button" type="button" data-back-action-menu><svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg>Kembali ke daftar action</button><div class="selected-step" data-selected-step hidden><span>Action dipilih</span><strong data-selected-step-label></strong></div></div>

        <section class="action-field-section inventory-multi-picker" data-inventory-picker hidden>
          <div class="picker-heading"><div><h3>Pilih kontainer / barang</h3><p>Cari berdasarkan nomor penetapan, nomor kontainer, atau uraian barang.</p></div><strong data-picker-count>0 barang dipilih</strong></div>
          <div class="picker-controls">
            <label class="search-field large"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" data-inventory-picker-search placeholder="Cari kontainer, nomor penetapan, atau uraian…" autocomplete="off"></label>
            <div class="picker-selection-toolbar"><label class="picker-select-all"><input type="checkbox" data-picker-select-all><span>Pilih semua hasil yang tampil</span></label><button type="button" class="picker-clear" data-picker-clear>Kosongkan pilihan</button></div>
          </div>
          <div class="multi-picker-list" data-inventory-picker-list>
            <?php $__range13 = tpl_iter(tpl_get($ctx, 'EligibleItems')); if (count($__range13) > 0): $__parent13 = $ctx; foreach ($__range13 as $__key13 => $__item13): $ctx = $__item13; ?>
            <label class="multi-picker-item" data-picker-item data-search="<?= tpl_escape(tpl_lower(tpl_get($ctx, 'DeterminationNo'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'ContainerNo'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'Description'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'ResearchRequestNo'))) ?>" data-item-type="<?= tpl_escape(tpl_get($ctx, 'Type')) ?>" data-item-status="<?= tpl_escape(tpl_get($ctx, 'StatusCode')) ?>" data-item-status-label="<?= tpl_escape(tpl_get($ctx, 'StatusLabel')) ?>" data-current-disposition="<?= tpl_escape(tpl_get($ctx, 'CurrentDisposition')) ?>" data-item-request="<?= tpl_escape(tpl_get($ctx, 'ResearchRequestNo')) ?>" data-allocation-proposal="<?= tpl_escape(tpl_get($ctx, 'AllocationProposalNo')) ?>" data-description="<?= tpl_escape(tpl_get($ctx, 'Description')) ?>" data-item-kind="<?= tpl_escape(tpl_get($ctx, 'ItemKind')) ?>" data-quantity="<?= tpl_escape(tpl_get($ctx, 'Quantity')) ?>" data-unit="<?= tpl_escape(tpl_get($ctx, 'Unit')) ?>">
              <input type="checkbox" name="inventory_ids[]" value="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>" data-picker-checkbox>
              <span><strong><?php if (tpl_truthy(tpl_get($ctx, 'ContainerNo'))): ?><?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?> · <?= tpl_escape(tpl_get($ctx, 'ContainerSize')) ?>'<?php else: ?>LCL · <?= tpl_escape(tpl_number(tpl_get($ctx, 'EstimatedVolumeM3'))) ?> m³<?php endif; ?></strong><small><?= tpl_escape(tpl_get($ctx, 'Type')) ?> · <?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?></small><em><?= tpl_escape(tpl_get($ctx, 'Description')) ?></em></span>
              <i><?= tpl_escape(tpl_get($ctx, 'StatusLabel')) ?></i>
            </label>
            <?php $ctx = $__parent13; endforeach; endif; ?>
          </div>
          <p class="picker-empty" data-picker-empty hidden>Tidak ada barang yang sesuai dengan action atau pencarian.</p>
        </section>

        <section class="action-field-section relocation-picker" data-relocation-picker hidden>
          <div class="picker-heading"><div><h3>Pilih target bongkar/muat</h3><p>Target FCL ditampilkan <strong>satu kali per kontainer</strong>. Setelah kontainer dipilih, seluruh uraian barang di dalamnya akan muncul dan wajib dialokasikan. Target LCL tetap dipilih per uraian barang.</p></div><strong data-relocation-source-count>0 target dipilih</strong></div>
          <input type="hidden" name="container_relocation_json" data-relocation-json disabled>
          <div class="picker-controls relocation-picker-controls"><label>Mode proses <em>*</em><select data-relocation-mode><option value="bongkar">Bongkar / pindah kontainer</option><option value="muat">Muat ke kontainer</option></select></label><label class="search-field large"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" data-relocation-search placeholder="Cari nomor kontainer, penetapan, atau uraian barang…" autocomplete="off"></label></div>
          <div class="relocation-source-list" data-relocation-source-list>
            <?php $__range14 = tpl_iter(tpl_get($ctx, 'RelocationTargetGroups')); if (count($__range14) > 0): $__parent14 = $ctx; foreach ($__range14 as $__key14 => $__item14): $ctx = $__item14; ?><?php $group = $ctx; ?>
            <article class="relocation-source-item" data-relocation-source data-source-key="<?= tpl_escape(tpl_get($ctx, 'TargetKey')) ?>" data-search="<?= tpl_escape(tpl_lower(tpl_get($ctx, 'DeterminationNo'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'ContainerNo'))) ?> <?php $__range15 = tpl_iter(tpl_get($ctx, 'Items')); if (count($__range15) > 0): $__parent15 = $ctx; foreach ($__range15 as $__key15 => $__item15): $ctx = $__item15; ?><?= tpl_escape(tpl_lower(tpl_get($ctx, 'Description'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'DeterminationNo'))) ?> <?php $ctx = $__parent15; endforeach; endif; ?>" data-load-type="<?= tpl_escape(tpl_get($ctx, 'LoadType')) ?>" data-container-no="<?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?>" data-container-size="<?= tpl_escape(tpl_get($ctx, 'ContainerSize')) ?>" data-determination-no="<?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?>" data-item-type="<?= tpl_escape(tpl_get($ctx, 'InventoryType')) ?>">
              <label class="relocation-source-select"><input type="checkbox" data-relocation-source-checkbox disabled><span><strong><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?><?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?> · <?= tpl_escape(tpl_container_size_label(tpl_get($ctx, 'ContainerSize'))) ?><?php else: ?>LCL · <?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?><?php endif; ?></strong><small><?= tpl_escape(tpl_get($ctx, 'InventoryType')) ?> · <?= tpl_escape(tpl_len(tpl_get($ctx, 'Items'))) ?> uraian barang · <?= tpl_escape(tpl_get($ctx, 'StatusLabel')) ?></small><em><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?>Pilih sekali untuk mengalokasikan seluruh uraian dalam kontainer<?php else: ?><?php $__with16 = tpl_index(tpl_get($ctx, 'Items'), 0); if (tpl_truthy($__with16)): $__parent16 = $ctx; $ctx = $__with16; ?><?= tpl_escape(tpl_get($ctx, 'Description')) ?><?php $ctx = $__parent16; endif; ?><?php endif; ?></em></span><i><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?>Sumber FCL<?php else: ?>Sumber LCL<?php endif; ?></i></label>
              <div data-relocation-source-items hidden>
                <?php $__range17 = tpl_iter(tpl_get($ctx, 'Items')); if (count($__range17) > 0): $__parent17 = $ctx; foreach ($__range17 as $__key17 => $__item17): $ctx = $__item17; ?><span data-relocation-source-item data-inventory-id="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>" data-load-type="<?= tpl_escape(tpl_get($ctx, 'LoadType')) ?>" data-container-no="<?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?>" data-container-size="<?= tpl_escape(tpl_get($ctx, 'ContainerSize')) ?>" data-volume="<?= tpl_escape(tpl_get($ctx, 'EstimatedVolumeM3')) ?>" data-quantity="<?= tpl_escape(tpl_get($ctx, 'Quantity')) ?>" data-unit="<?= tpl_escape(tpl_get($ctx, 'Unit')) ?>" data-goods-value="<?= tpl_escape(tpl_get($ctx, 'GoodsValue')) ?>" data-description="<?= tpl_escape(tpl_get($ctx, 'Description')) ?>" data-determination-no="<?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?>"></span><?php $ctx = $__parent17; endforeach; endif; ?>
              </div>
            </article>
            <?php $ctx = $__parent14; endforeach; else: ?><div class="picker-empty static-empty">Belum ada inventory yang dapat diproses.</div><?php endif; ?>
          </div>
          <p class="picker-empty" data-relocation-empty hidden>Target tidak ditemukan atau tidak memenuhi syarat mode bongkar/muat yang dipilih.</p>
          <div class="relocation-editor-list" data-relocation-editor-list hidden></div>

          <template data-relocation-operation-template>
            <article class="relocation-operation-card" data-relocation-operation>
              <section class="relocation-group-summary"><div><span>Target terpilih</span><strong data-relocation-group-title>—</strong><small data-relocation-group-subtitle>—</small></div><strong data-relocation-group-count>0 uraian</strong></section>
              <div class="relocation-item-editor-list" data-relocation-item-editor-list></div>
            </article>
          </template>

          <template data-relocation-item-template>
            <section class="relocation-item-operation" data-relocation-item-operation>
              <section class="relocation-source-summary"><div><span>Uraian sumber</span><strong data-relocation-source-title>—</strong><small data-relocation-source-description>—</small></div><div><span>Kuantitas wajib dialokasikan</span><strong data-relocation-required-quantity>0</strong><small data-relocation-mode-copy>Jumlah seluruh tujuan harus sama persis.</small></div></section>
              <div class="container-entry-heading"><div><h3 data-relocation-destination-title>Tujuan bongkar/muat</h3><p data-relocation-destination-help>Tambahkan satu atau beberapa tujuan.</p></div><strong data-relocation-allocation-count>0 tujuan</strong></div>
              <div class="relocation-allocation-list" data-relocation-allocation-list></div>
              <button class="button secondary compact" type="button" data-add-relocation-allocation>+ Tambah tujuan</button>
              <div class="relocation-total-bar" data-relocation-total-bar><span>Total dialokasikan</span><strong data-relocation-total>0</strong><em data-relocation-balance>Belum sesuai</em></div>
            </section>
          </template>

          <template data-relocation-allocation-template>
            <section class="relocation-allocation-row" data-relocation-allocation-row>
              <header><strong data-relocation-row-title>Tujuan</strong><button type="button" class="remove-line-button" data-remove-relocation-allocation>Hapus</button></header>
              <div class="form-grid cols-2">
                <label>Jenis penempatan <em>*</em><select data-relocation-field="load_type"><option value="FCL">FCL — dalam kontainer</option><option value="LCL">LCL — dibongkar ke gudang</option></select></label>
                <label>Kuantitas <em>*</em><input type="number" min="0.01" step="0.01" data-relocation-field="quantity" placeholder="0"></label>
                <label data-relocation-container-field>Nomor kontainer <em>*</em><input data-relocation-field="container_no" placeholder="Contoh: ABCD 123456-7"></label>
                <label data-relocation-container-field>Ukuran kontainer <em>*</em><select data-relocation-field="container_size"><option value="">Pilih ukuran</option><option value="20">20'</option><option value="40">40'</option><option value="40HC">40' HC</option><option value="45HC">45' HC</option></select></label>
                <label class="span-2" data-relocation-volume-field hidden>Perkiraan volume LCL <em>*</em><input type="number" min="0.01" step="0.01" data-relocation-field="estimated_volume_m3" placeholder="Contoh: 4.5"><small class="field-inline-help">Satuan meter kubik (m³), digunakan untuk perhitungan SOR.</small></label>
              </div>
            </section>
          </template>
        </section>

        <section class="action-field-section census-target-picker" data-census-target-picker hidden>
          <div class="picker-heading"><div><h3>Pilih target pencacahan</h3><p>FCL dicari dan dipilih per nomor kontainer; LCL dicari dan dipilih per uraian barang. Setiap target mempunyai input hasil pencacahan sendiri.</p></div><strong data-census-picker-count>0 target dipilih</strong></div>
          <input type="hidden" name="census_results_json" data-census-results-json disabled>
          <div class="picker-controls"><label class="search-field large"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" data-census-target-search placeholder="Cari nomor kontainer FCL atau uraian barang LCL…" autocomplete="off"></label></div>
          <div class="census-target-list">
            <?php $__range18 = tpl_iter(tpl_get($ctx, 'CensusTargetGroups')); if (count($__range18) > 0): $__parent18 = $ctx; foreach ($__range18 as $__key18 => $__item18): $ctx = $__item18; ?>
            <article class="census-target-card" data-census-target-card data-target-id="<?= tpl_escape(tpl_get($ctx, 'TargetID')) ?>" data-load-type="<?= tpl_escape(tpl_get($ctx, 'LoadType')) ?>" data-census-search="<?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?><?= tpl_escape(tpl_lower(tpl_get($ctx, 'ContainerNo'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'DeterminationNo'))) ?><?php else: ?><?php $__range19 = tpl_iter(tpl_get($ctx, 'Items')); if (count($__range19) > 0): $__parent19 = $ctx; foreach ($__range19 as $__key19 => $__item19): $ctx = $__item19; ?><?= tpl_escape(tpl_lower(tpl_get($ctx, 'Description'))) ?> <?= tpl_escape(tpl_lower(tpl_get($ctx, 'DeterminationNo'))) ?> <?php $ctx = $__parent19; endforeach; endif; ?><?php endif; ?>">
              <label class="census-target-select"><input type="checkbox" data-census-target-checkbox><span><strong><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?><?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?> · <?= tpl_escape(tpl_container_size_label(tpl_get($ctx, 'ContainerSize'))) ?><?php else: ?>LCL · <?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?><?php endif; ?></strong><small><?= tpl_escape(tpl_get($ctx, 'InventoryType')) ?> · <?= tpl_escape(tpl_len(tpl_get($ctx, 'Items'))) ?> uraian tersimpan · <?= tpl_escape(tpl_get($ctx, 'StatusLabel')) ?></small></span><i><?= tpl_escape(tpl_get($ctx, 'LoadType')) ?></i></label>
              <div class="census-target-editor" data-census-target-editor hidden>
                <div class="census-target-editor-heading"><div><strong>Detail hasil pencacahan</strong><p><?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?>Uraian tersimpan otomatis ditampilkan. Tambahkan detail baru apabila ditemukan barang lain dalam kontainer.<?php else: ?>Perbarui hasil pencacahan untuk barang LCL ini.<?php endif; ?></p></div></div>
                <div data-census-target-lines>
                  <?php $__range20 = tpl_iter(tpl_get($ctx, 'Items')); if (count($__range20) > 0): $__parent20 = $ctx; foreach ($__range20 as $__key20 => $__item20): $ctx = $__item20; ?><?php $item = $ctx; ?>
                  <section class="census-result-line" data-census-result-line data-inventory-id="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>" data-existing="true">
                    <header><strong>Uraian tersimpan</strong><span><?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?></span></header>
                    <div class="form-grid cols-2">
                      <label class="span-2">Uraian barang <em>*</em><textarea rows="2" data-census-field="description" disabled><?= tpl_escape(tpl_get($ctx, 'Description')) ?></textarea></label>
                      <label>Jenis barang <em>*</em><select data-census-field="item_kind" disabled><option value="">Pilih jenis barang</option><?php $__range21 = tpl_iter(tpl_get($root, 'ItemKindNames')); if (count($__range21) > 0): $__parent21 = $ctx; foreach ($__range21 as $__key21 => $__item21): $ctx = $__item21; ?><option value="<?= tpl_escape($ctx) ?>" <?php if (tpl_truthy(tpl_eq($ctx, tpl_get($item, 'ItemKind')))): ?>selected<?php endif; ?>><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent21; endforeach; endif; ?></select></label>
                      <label>Nilai awal barang<input inputmode="numeric" data-census-field="goods_value" value="<?= tpl_escape(tpl_get($ctx, 'GoodsValue')) ?>" disabled></label>
                      <label>Jumlah <em>*</em><input type="number" step="0.01" min="0.01" value="<?= tpl_escape(tpl_get($ctx, 'Quantity')) ?>" data-census-field="quantity" disabled></label>
                      <label class="span-2">Detail jumlah barang <span class="optional-label">Opsional</span><input data-census-field="quantity_detail" value="<?= tpl_escape(tpl_get($ctx, 'QuantityDetail')) ?>" placeholder="Contoh: 12 karton @ 24 botol" disabled></label>
                      <label>Satuan <em>*</em><select data-census-field="unit" disabled><option value="">Pilih satuan</option><?php $__range22 = tpl_iter(tpl_get($root, 'UnitNames')); if (count($__range22) > 0): $__parent22 = $ctx; foreach ($__range22 as $__key22 => $__item22): $ctx = $__item22; ?><option value="<?= tpl_escape($ctx) ?>" <?php if (tpl_truthy(tpl_eq($ctx, tpl_get($item, 'Unit')))): ?>selected<?php endif; ?>><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent22; endforeach; endif; ?></select></label>
                      <label>Kondisi barang <em>*</em><select data-census-field="goods_condition" disabled><option value="">Pilih kondisi</option><?php $__range23 = tpl_iter(tpl_get($root, 'GoodsConditionNames')); if (count($__range23) > 0): $__parent23 = $ctx; foreach ($__range23 as $__key23 => $__item23): $ctx = $__item23; ?><option value="<?= tpl_escape($ctx) ?>" <?php if (tpl_truthy(tpl_eq($ctx, tpl_get($item, 'GoodsCondition')))): ?>selected<?php endif; ?>><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent23; endforeach; endif; ?></select></label>
                    </div>
                  </section>
                  <?php $ctx = $__parent20; endforeach; endif; ?>
                </div>
                <?php if (tpl_truthy(tpl_eq(tpl_get($ctx, 'LoadType'), 'FCL'))): ?><button class="button secondary compact" type="button" data-add-census-target-line disabled>+ Tambah detail uraian baru</button><?php endif; ?>
              </div>
            </article>
            <?php $ctx = $__parent18; endforeach; else: ?><div class="picker-empty static-empty">Belum ada inventory yang dapat dicacah.</div><?php endif; ?>
          </div>
          <p class="picker-empty" data-census-target-empty hidden>Kontainer atau barang LCL tidak ditemukan.</p>
          <template data-census-result-line-template><section class="census-result-line new-line" data-census-result-line data-inventory-id="" data-existing="false"><header><strong>Uraian baru hasil pencacahan</strong><button type="button" class="remove-line-button" data-remove-census-target-line>Hapus</button></header><div class="form-grid cols-2"><label class="span-2">Uraian barang <em>*</em><textarea rows="2" data-census-field="description"></textarea></label><label>Jenis barang <em>*</em><select data-census-field="item_kind"><option value="">Pilih jenis barang</option><?php $__range24 = tpl_iter(tpl_get($ctx, 'ItemKindNames')); if (count($__range24) > 0): $__parent24 = $ctx; foreach ($__range24 as $__key24 => $__item24): $ctx = $__item24; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent24; endforeach; endif; ?></select></label><label>Nilai awal barang<input inputmode="numeric" data-census-field="goods_value"></label><label>Jumlah <em>*</em><input type="number" step="0.01" min="0.01" data-census-field="quantity"></label><label class="span-2">Detail jumlah barang <span class="optional-label">Opsional</span><input data-census-field="quantity_detail" placeholder="Contoh: 12 karton @ 24 botol"></label><label>Satuan <em>*</em><select data-census-field="unit"><option value="">Pilih satuan</option><?php $__range25 = tpl_iter(tpl_get($ctx, 'UnitNames')); if (count($__range25) > 0): $__parent25 = $ctx; foreach ($__range25 as $__key25 => $__item25): $ctx = $__item25; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent25; endforeach; endif; ?></select></label><label>Kondisi barang <em>*</em><select data-census-field="goods_condition"><option value="">Pilih kondisi</option><?php $__range26 = tpl_iter(tpl_get($ctx, 'GoodsConditionNames')); if (count($__range26) > 0): $__parent26 = $ctx; foreach ($__range26 as $__key26 => $__item26): $ctx = $__item26; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent26; endforeach; endif; ?></select></label></div></section></template>
        </section>

        <section class="action-field-section pfpd-request-picker" data-pfpd-request-picker hidden>
          <div class="picker-heading"><div><h3>Pilih nomor request penelitian PFPD</h3><p>Klik nomor request untuk membuka seluruh kontainer dan uraian barang yang harus diteliti.</p></div><strong data-pfpd-picker-count>0 request dipilih</strong></div>
          <input type="hidden" name="pfpd_results_json" data-pfpd-results-json disabled>
          <div class="picker-controls pfpd-picker-controls">
            <label class="search-field large"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" data-pfpd-request-search placeholder="Cari nomor request penelitian PFPD…" autocomplete="off"></label>
          </div>
          <div class="pfpd-request-list">
            <?php $__range27 = tpl_iter(tpl_get($ctx, 'ResearchRequestGroups')); if (count($__range27) > 0): $__parent27 = $ctx; foreach ($__range27 as $__key27 => $__item27): $ctx = $__item27; ?>
            <article class="pfpd-request-card" data-pfpd-request-card data-request-no="<?= tpl_escape(tpl_get($ctx, 'RequestNo')) ?>" data-pfpd-search="<?= tpl_escape(tpl_lower(tpl_get($ctx, 'RequestNo'))) ?>">
              <button type="button" class="pfpd-request-button" data-pfpd-request-button>
                <span><strong><?= tpl_escape(tpl_get($ctx, 'RequestNo')) ?></strong><small><?= tpl_escape(tpl_date(tpl_get($ctx, 'RequestDate'))) ?> · <?= tpl_escape(tpl_len(tpl_get($ctx, 'Items'))) ?> uraian barang</small></span>
                <svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>
              </button>
              <div class="pfpd-request-items" data-pfpd-request-items hidden>
                <?php $__range28 = tpl_iter(tpl_get($ctx, 'Items')); if (count($__range28) > 0): $__parent28 = $ctx; foreach ($__range28 as $__key28 => $__item28): $ctx = $__item28; ?>
                <section class="pfpd-result-row" data-pfpd-result-row data-inventory-id="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>">
                  <header><div><strong><?php if (tpl_truthy(tpl_get($ctx, 'ContainerNo'))): ?><?= tpl_escape(tpl_get($ctx, 'ContainerNo')) ?> · <?= tpl_escape(tpl_container_size_label(tpl_get($ctx, 'ContainerSize'))) ?><?php else: ?>LCL · <?= tpl_escape(tpl_number(tpl_get($ctx, 'EstimatedVolumeM3'))) ?> m³<?php endif; ?></strong><small><?= tpl_escape(tpl_get($ctx, 'DeterminationNo')) ?></small></div><p><?= tpl_escape(tpl_get($ctx, 'Description')) ?></p></header>
                  <div class="form-grid cols-2">
                    <label>Kode HS <em>*</em><input data-pfpd-field="hs_code" disabled placeholder="Contoh: 8471.30.90"></label>
                    <label>Apakah lartas? <em>*</em><select data-pfpd-field="is_restricted" disabled><option value="">Pilih status</option><option value="tidak">Tidak</option><option value="ya">Ya</option></select></label>
                    <label class="span-2" data-pfpd-restriction-wrapper hidden>Keterangan lartas <em>*</em><input data-pfpd-field="restriction_rule" disabled placeholder="Isi jenis atau dasar peraturan lartas"></label>
                    <label class="span-2">Nilai barang <em>*</em><input inputmode="numeric" data-pfpd-field="goods_value" disabled placeholder="Contoh: 250000000"></label>
                  </div>
                </section>
                <?php $ctx = $__parent28; endforeach; endif; ?>
              </div>
            </article>
            <?php $ctx = $__parent27; endforeach; else: ?><div class="picker-empty static-empty">Belum ada nomor request PFPD yang menunggu penelitian.</div><?php endif; ?>
          </div>
          <p class="picker-empty" data-pfpd-search-empty hidden>Nomor request penelitian PFPD tidak ditemukan.</p>
        </section>

        <div class="action-fields" data-action-fields hidden>
          <section class="action-field-section"><h3>Dokumen terkait</h3><div class="form-grid cols-2"><label data-document-label>Nomor dokumen <em>*</em><input name="document_no" required disabled></label><label>Tanggal dokumen <em>*</em><input type="date" name="document_date" value="<?= tpl_escape(tpl_isodate(tpl_get($ctx, 'Now'))) ?>" required disabled></label><label class="span-2 document-upload-field">Upload dokumen <span class="optional-mark">Opsional</span><input type="file" name="document_file" accept="application/pdf,image/jpeg,image/png,image/webp,image/gif" disabled><small>PDF atau gambar, maksimal 8 MB. File dapat diunduh melalui timeline.</small></label></div></section>

          <section class="action-field-section" data-fields-for="pemindahan" hidden><h3>Lokasi tujuan</h3><div class="form-grid cols-2"><label>Pindah ke TPP <em>*</em><select name="target_facility_id" required disabled><option value="">Pilih TPP tujuan</option><?php $__range29 = tpl_iter(tpl_get($ctx, 'Facilities')); if (count($__range29) > 0): $__parent29 = $ctx; foreach ($__range29 as $__key29 => $__item29): $ctx = $__item29; ?><option value="<?= tpl_escape(tpl_get($ctx, 'ID')) ?>"><?= tpl_escape(tpl_get($ctx, 'Name')) ?></option><?php $ctx = $__parent29; endforeach; endif; ?></select></label><label>Blok TPP <span class="optional-mark">Opsional</span><input name="target_location" maxlength="160" disabled placeholder="Contoh: Blok B-08 / Gudang 2"></label></div><p class="field-help">Setelah disimpan, TPP tujuan dan blok opsional tercatat pada detail barang, perubahan data, serta pelaporan.</p></section>

          <section class="action-field-section" data-fields-for="pindah_bongkar_kontainer" hidden><h3>Bongkar / muat fisik barang</h3><p class="field-help">Pada mode bongkar, barang FCL dapat dipindah ke satu atau beberapa kontainer tujuan dan/atau dibongkar menjadi LCL di gudang. Pada mode muat, barang LCL dapat dimasukkan ke satu atau beberapa kontainer. Action tersedia untuk seluruh inventory aktif, termasuk barang yang sudah mulai lelang, musnah, hibah, atau PSP. Untuk menjaga keterkaitan proses, satu uraian yang sedang/sudah berproses hanya dapat dipindahkan ke satu tujuan per action.</p></section>

          <section class="action-field-section" data-fields-for="pencacahan" hidden><h3>Hasil pencacahan per target</h3><p class="field-help">Input uraian, jumlah, satuan, nilai, dan kondisi dilakukan pada setiap kontainer FCL atau barang LCL yang dipilih di bagian atas. Untuk FCL, uraian baru dapat ditambahkan tanpa menambah perhitungan kapasitas YOR.</p></section>

          <section class="action-field-section" data-fields-for="request_penelitian_pfpd" hidden><h3>Request Penelitian PFPD</h3><p class="field-help">Nomor dan tanggal dokumen di atas disimpan sebagai dasar penelitian PFPD. Seluruh uraian dalam kontainer fisik yang dipilih akan otomatis memakai nomor request yang sama.</p></section>

          <section class="action-field-section" data-fields-for="penelitian_pfpd" hidden><h3>Hasil Penelitian PFPD</h3><p class="field-help">Hasil diisi per kontainer dan per uraian melalui nomor request yang dipilih di atas.</p></section>

          <section class="action-field-section" data-fields-for="penetapan_bmmn" hidden><h3>Penetapan BMMN</h3><p class="field-help">Status berubah menjadi BMMN. Dokumen asal otomatis dicatat sebagai BCF 1.5 untuk asal BTD atau KEP BDN untuk asal BDN, beserta nomor dan tanggalnya.</p></section>

          <section class="action-field-section" data-fields-for="usulan_peruntukan_bmmn" hidden><h3>Usulan Peruntukan BMMN</h3><div class="form-grid"><label>Jenis Peruntukan <em>*</em><select name="allocation_type" required disabled><option value="">Pilih peruntukan</option><?php $__range30 = tpl_iter(tpl_get($ctx, 'AllocationPurposeNames')); if (count($__range30) > 0): $__parent30 = $ctx; foreach ($__range30 as $__key30 => $__item30): $ctx = $__item30; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent30; endforeach; endif; ?></select></label></div></section>
          <section class="action-field-section" data-fields-for="persetujuan_peruntukan_bmmn" hidden><h3>Persetujuan Peruntukan BMMN</h3><div class="form-grid"><label>Jenis Peruntukan <em>*</em><select name="allocation_type" required disabled><option value="">Pilih peruntukan</option><?php $__range31 = tpl_iter(tpl_get($ctx, 'AllocationPurposeNames')); if (count($__range31) > 0): $__parent31 = $ctx; foreach ($__range31 as $__key31 => $__item31): $ctx = $__item31; ?><option value="<?= tpl_escape($ctx) ?>"><?= tpl_escape($ctx) ?></option><?php $ctx = $__parent31; endforeach; endif; ?></select></label></div></section>

          <section class="action-field-section" data-fields-for="pengeluaran_barang" hidden><h3>Pengeluaran barang</h3><div class="form-grid"><label>Jenis pengeluaran <em>*</em><select name="exit_type" required disabled data-exit-type><option value="">Pilih jenis pengeluaran</option><?php $__range32 = tpl_iter(tpl_get($ctx, 'ExitOptions')); if (count($__range32) > 0): $__parent32 = $ctx; foreach ($__range32 as $__key32 => $__item32): $ctx = $__item32; ?><option value="<?= tpl_escape(tpl_get($ctx, 'Code')) ?>" data-types="<?= tpl_escape(tpl_get($ctx, 'Types')) ?>"><?= tpl_escape(tpl_get($ctx, 'Label')) ?></option><?php $ctx = $__parent32; endforeach; endif; ?></select></label></div><p class="field-help">Pilihan otomatis disesuaikan dengan jenis BTD, BDN, BMMN, atau barang titipan yang dipilih.</p><p class="field-help danger-text">Setelah disimpan, barang keluar dari daftar inventory aktif.</p></section>

          <section class="action-field-section"><h3>Catatan</h3><div class="form-grid"><label>Keterangan tambahan<textarea name="notes" rows="3" placeholder="Opsional"></textarea></label></div></section>
        </div>
        </section>
      </div>
      <footer class="modal-footer action-modal-footer"><button class="button ghost" type="button" data-close-modal>Batal</button><button class="button primary" type="submit" disabled hidden data-submit-step data-action-submit>Simpan tindak lanjut</button></footer>
    </form>
  </section>
</div>
<?php endif; ?>
<?php endif; ?>

