<?php
declare(strict_types=1);
namespace Livira\Domain;

final class Domain
{
    public const TYPES=['BTD','BDN','BMMN','TITIPAN'];
    public const DISPOSITIONS=['lelang','musnah','hibah'];
    public const ENTRUSTED_CATEGORIES=['BTD','BDN','BMMN','Tidak Teridentifikasi'];
    public const BDN_CATEGORIES=['Barang Lartas Ps. 53 (4)','Barang/Sarkut yg Ditegah Pejabat BC','Barang/Sarkut yg Ditinggalkan di KP','BKC & Barang Lain yg berasal dari Pelanggar Tidak Dikenal','BKC yg berasal dari pemilik tidak diketahui'];
    public const ITEM_KINDS=['Barang Umum','Barang Berbahaya (B3)','Hewan atau Tumbuhan Hidup','Barang Peka Waktu','Barang Berharga'];
    public const GOODS_CONDITIONS=['Baru','Bekas','Rusak','Segar','Busuk'];
    public const ALLOCATION_PURPOSES=['Lelang','Musnah','Hibah','PSP'];
    public const TPS_NAMES=['PT Agung Raya','PT Indonesian Air & Marine Supply (Utara)','PT Indonesian Air & Marine Supply (Barat)','PT Pelabuhan Indonesia II (Persero)','PT Indofood Sukses Makmur Tbk','PT Lautan Tirta Transportama','PT Multi Terminal Indonesia (CDC Banda)','PT Pelabuhan Tanjung Priok (Ambon)','PT Pelabuhan Tanjung Priok (101-101U)','PT IPC Terminal Petikemas (Terminal 3)','PT. Pelabuhan Indonesia (Persero) Regional 2 Tanjung Priok','PT Primanata Jasa Persada','PT Wira Mitra Prima','PT Pelabuhan Indonesia II (Persero) (NPCT1)','PT Pesaka Loka Kirana','PT Dharma Kartika Bhakti','PT Inti Mandiri Utama Trans','PT Agung Raya (Barat)'];
    public const UNITS=['Ampoule','Bobbin','Bundle','Bag','Bale','Barrel (petroleum) (458,987 dm3)','Bottle','Box','Can','Coil','Centimetre','Crate','Case','Carton','Drum','Dozen','Gram','Kilogram','Litre ( 1 dm3 )','Milligram','Millilitre','Millimetre','Square metre','Cubic metre','Metre','Unpacked or unpackaged','Number of international units','number of pairs','Piece','Pail','Tray / Tray Pack','Pallet','Roll','Reel','Sack','Set','Sheet','Stick, cigarette','Metric ton (1000 kg)','Bulk, liquid','Yard (0.9144 m)'];
    public const LOAD_TYPES=[['Code'=>'FCL','Label'=>'FCL','Types'=>''],['Code'=>'LCL','Label'=>'LCL','Types'=>'']];
    public const CONTAINER_SIZES=[['Code'=>'20','Label'=>"20'",'Types'=>''],['Code'=>'40','Label'=>"40'",'Types'=>''],['Code'=>'40HC','Label'=>"40' HC",'Types'=>''],['Code'=>'45HC','Label'=>"45' HC",'Types'=>'']];
    public const TRANSFER_TYPES=[['Code'=>'hibah','Label'=>'Hibah','Types'=>'BMMN'],['Code'=>'psp','Label'=>'PSP','Types'=>'BMMN']];
    public const EXIT_OPTIONS=[
        ['Code'=>'impor_untuk_dipakai','Label'=>'IMPOR UTK DIPAKAI','Types'=>'BTD'],['Code'=>'reekspor','Label'=>'REEKSPOR','Types'=>'BTD,BDN'],['Code'=>'batal_ekspor','Label'=>'BATAL EKSPOR','Types'=>'BTD'],['Code'=>'ekspor','Label'=>'EKSPOR','Types'=>'BTD'],['Code'=>'keluarkan_ke_tpb','Label'=>'KELUARKAN KE TPB','Types'=>'BTD'],['Code'=>'lelang','Label'=>'LELANG','Types'=>'BTD,BDN,BMMN'],['Code'=>'musnah','Label'=>'MUSNAH','Types'=>'BTD,BDN,BMMN'],['Code'=>'psp','Label'=>'PSP','Types'=>'BTD,BDN,BMMN'],['Code'=>'hibah','Label'=>'HIBAH','Types'=>'BTD,BDN,BMMN'],['Code'=>'diserahkan_ke_aph_lain','Label'=>'DISERAHKAN KE APH LAIN','Types'=>'BTD,BDN'],['Code'=>'pembatalan_bdn','Label'=>'PEMBATALAN BDN','Types'=>'BDN'],['Code'=>'diserahkan_ke_ppns','Label'=>'DISERAHKAN KE PPNS','Types'=>'BDN'],['Code'=>'penghapusan','Label'=>'PENGHAPUSAN','Types'=>'BMMN'],['Code'=>'pengeluaran_barang_titipan','Label'=>'PENGELUARAN BARANG TITIPAN','Types'=>'TITIPAN'],
    ];
    public const INVENTORY_ACTIONS=[
        ['Code'=>'pemindahan','Label'=>'Pemindahan','Description'=>'Pindahkan barang dari TPS atau TPP asal ke TPP tujuan dan perbarui lokasi.','Document'=>'No. ST/SPRIN/BA','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'pindah_bongkar_kontainer','Label'=>'Bongkar/Muat Kontainer','Description'=>'Bongkar barang FCL ke kontainer lain atau ke gudang (LCL), serta muat barang LCL di gudang ke dalam kontainer.','Document'=>'No. BA/ST pemindahan','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'pemberitahuan','Label'=>'Pemberitahuan','Description'=>'Catat surat pemberitahuan BTD atau BDN.','Document'=>'Nomor surat','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'pencacahan','Label'=>'Pencacahan','Description'=>'Periksa dan perbarui uraian, jumlah, satuan, serta jenis barang.','Document'=>'No. BA Cacah','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'request_penelitian_pfpd','Label'=>'Request Penelitian PFPD','Description'=>'Buat dokumen permintaan penelitian kepada PFPD.','Document'=>'Nomor dokumen request','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'penelitian_pfpd','Label'=>'Penelitian PFPD','Description'=>'Catat HS, lartas, keterangan lartas, dan nilai barang berdasarkan request.','Document'=>'Nomor dokumen penelitian','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'penetapan_bmmn','Label'=>'Penetapan BMMN','Description'=>'Ubah BTD atau BDN menjadi BMMN dan pertahankan jenis asalnya.','Document'=>'No. SKEP BMMN','BMMNOnly'=>false,'NonBMMNOnly'=>true,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'usulan_peruntukan_bmmn','Label'=>'Usulan Peruntukan','Description'=>'Catat jenis peruntukan serta nomor dan tanggal dokumen usulan.','Document'=>'No. Dok. Usulan','BMMNOnly'=>true,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'persetujuan_peruntukan_bmmn','Label'=>'Persetujuan Peruntukan','Description'=>'Catat jenis peruntukan serta nomor dan tanggal dokumen persetujuan.','Document'=>'No. Dok. Persetujuan','BMMNOnly'=>true,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
        ['Code'=>'pengeluaran_barang','Label'=>'Pengeluaran Barang','Description'=>'Catat dokumen, tanggal, jenis pengeluaran, dan keluarkan barang dari inventory aktif.','Document'=>'Nomor dokumen pengeluaran','BMMNOnly'=>false,'NonBMMNOnly'=>false,'CreatesProcess'=>false,'AllowedStatus'=>''],
    ];
    public const AUCTION_ACTIONS=[['Code'=>'kep_lelang','Label'=>'Penerbitan KEP Lelang','Description'=>'Tetapkan barang inventory yang masuk ke proses lelang.','Document'=>'No. KEP Lelang','CreatesProcess'=>true,'AllowedStatus'=>''],['Code'=>'kep_htl','Label'=>'Penerbitan KEP Harga Terendah Lelang','Description'=>'Tetapkan nilai HTL tanpa mengganti nilai penelitian PFPD.','Document'=>'No. KEP HTL','CreatesProcess'=>false,'AllowedStatus'=>'kep_lelang'],['Code'=>'jadwal_lelang','Label'=>'Penjadwalan Lelang','Description'=>'Catat ND jadwal dan tanggal pelaksanaan tunggal atau rentang tanggal.','Document'=>'No. ND Jadwal Lelang','CreatesProcess'=>false,'AllowedStatus'=>'kep_htl,lelang_penyesuaian'],['Code'=>'selesai_lelang','Label'=>'Selesai Lelang','Description'=>'Catat risalah serta hasil laku atau tidak laku.','Document'=>'No. Risalah Lelang','CreatesProcess'=>false,'AllowedStatus'=>'jadwal_lelang'],['Code'=>'lelang_penyesuaian','Label'=>'Lelang Penyesuaian','Description'=>'Mulai putaran penyesuaian khusus barang berstatus tidak laku.','Document'=>'No. KEP Lelang Penyesuaian','CreatesProcess'=>false,'AllowedStatus'=>'tidak_laku'],['Code'=>'alokasi_hasil_lelang','Label'=>'Alokasi Hasil Lelang','Description'=>'Catat KEP dan tujuan alokasi hasil untuk barang yang laku.','Document'=>'No. KEP Alokasi Hasil Lelang','CreatesProcess'=>false,'AllowedStatus'=>'laku']];
    public const DESTRUCTION_ACTIONS=[['Code'=>'kep_musnah','Label'=>'Penerbitan KEP Musnah','Description'=>'Catat KEP Musnah, tanggal, biaya, dan barang yang dimusnahkan.','Document'=>'No. KEP Musnah','CreatesProcess'=>true,'AllowedStatus'=>''],['Code'=>'ba_musnah','Label'=>'Berita Acara Musnah','Description'=>'Catat BA Musnah, tanggal, dan biaya pelaksanaan pemusnahan.','Document'=>'No. BA Musnah','CreatesProcess'=>false,'AllowedStatus'=>'kep_musnah']];
    public const GRANT_ACTIONS=[['Code'=>'ba_serah_terima','Label'=>'Berita Acara Serah Terima','Description'=>'Catat jenis Hibah/PSP, nomor BA, tanggal, dan barang yang diserahterimakan.','Document'=>'No. BA Serah Terima','CreatesProcess'=>true,'AllowedStatus'=>'']];

    public const PERMISSIONS=[
        ['Code'=>'dashboard.view','Group'=>'Umum','Label'=>'Lihat dashboard','Description'=>'Melihat ringkasan inventory dan progres penyelesaian.'],['Code'=>'dashboard.capacity.manage','Group'=>'Umum','Label'=>'Edit kapasitas YOR/SOR','Description'=>'Mengubah kapasitas penampungan YOR dan SOR setiap TPP dari dashboard.'],['Code'=>'inventory.view','Group'=>'Inventory','Label'=>'Lihat inventory','Description'=>'Melihat daftar dan detail barang.'],
        ['Code'=>'inventory.create.btd','Group'=>'Inventory — Input awal','Label'=>'Pencatatan BTD','Description'=>'Mencatat BTD baru secara manual maupun melalui upload Excel.'],['Code'=>'inventory.create.bdn','Group'=>'Inventory — Input awal','Label'=>'Penetapan BDN','Description'=>'Mencatat penetapan BDN baru secara manual maupun melalui upload Excel.'],['Code'=>'inventory.create.titipan','Group'=>'Inventory — Input awal','Label'=>'Pemasukan barang titipan','Description'=>'Mencatat barang titipan kantor atau unit lain.'],
        ['Code'=>'inventory.action.pemindahan','Group'=>'Inventory — Action','Label'=>'Action pemindahan','Description'=>'Memindahkan barang ke TPP tujuan.'],['Code'=>'inventory.action.bongkar_muat','Group'=>'Inventory — Action','Label'=>'Action bongkar/muat kontainer','Description'=>'Mengubah penempatan fisik FCL/LCL.'],['Code'=>'inventory.action.pemberitahuan','Group'=>'Inventory — Action','Label'=>'Action pemberitahuan','Description'=>'Mencatat surat pemberitahuan.'],['Code'=>'inventory.action.pencacahan','Group'=>'Inventory — Action','Label'=>'Action pencacahan','Description'=>'Mencatat hasil pencacahan.'],['Code'=>'inventory.action.request_penelitian_pfpd','Group'=>'Inventory — Action','Label'=>'Action request penelitian PFPD','Description'=>'Membuat permintaan penelitian PFPD.'],['Code'=>'inventory.action.penelitian_pfpd','Group'=>'Inventory — Action','Label'=>'Action penelitian PFPD','Description'=>'Mencatat hasil penelitian PFPD.'],['Code'=>'inventory.action.penetapan_bmmn','Group'=>'Inventory — Action','Label'=>'Action penetapan BMMN','Description'=>'Mengubah BTD/BDN menjadi BMMN.'],['Code'=>'inventory.action.usulan_peruntukan_bmmn','Group'=>'Inventory — Action','Label'=>'Action usulan peruntukan BMMN','Description'=>'Mencatat usulan peruntukan.'],['Code'=>'inventory.action.persetujuan_peruntukan_bmmn','Group'=>'Inventory — Action','Label'=>'Action persetujuan peruntukan BMMN','Description'=>'Mencatat persetujuan peruntukan.'],['Code'=>'inventory.action.pengeluaran_barang','Group'=>'Inventory — Action','Label'=>'Action pengeluaran barang','Description'=>'Mencatat pengeluaran barang.'],
        ['Code'=>'inventory.type.btd','Group'=>'Cakupan barang','Label'=>'Akses BTD','Description'=>'Mengakses BTD.'],['Code'=>'inventory.type.bdn','Group'=>'Cakupan barang','Label'=>'Akses BDN','Description'=>'Mengakses BDN.'],['Code'=>'inventory.type.bmmn','Group'=>'Cakupan barang','Label'=>'Akses BMMN','Description'=>'Mengakses BMMN.'],['Code'=>'inventory.type.titipan','Group'=>'Cakupan barang','Label'=>'Akses barang titipan','Description'=>'Mengakses barang titipan.'],
        ['Code'=>'reconciliation.view','Group'=>'Rekonsiliasi','Label'=>'Lihat rekonsiliasi','Description'=>'Melihat hasil rekonsiliasi.'],['Code'=>'reconciliation.manage','Group'=>'Rekonsiliasi','Label'=>'Kelola rekonsiliasi','Description'=>'Menambah/mengeluarkan/koreksi barang.'],['Code'=>'auction.view','Group'=>'Lelang','Label'=>'Lihat lelang','Description'=>'Melihat lelang.'],['Code'=>'auction.manage','Group'=>'Lelang','Label'=>'Kelola lelang','Description'=>'Mengelola lelang.'],['Code'=>'destruction.view','Group'=>'Pemusnahan','Label'=>'Lihat pemusnahan','Description'=>'Melihat pemusnahan.'],['Code'=>'destruction.manage','Group'=>'Pemusnahan','Label'=>'Kelola pemusnahan','Description'=>'Mengelola pemusnahan.'],['Code'=>'grant.view','Group'=>'Hibah / PSP','Label'=>'Lihat hibah / PSP','Description'=>'Melihat hibah/PSP.'],['Code'=>'grant.manage','Group'=>'Hibah / PSP','Label'=>'Kelola hibah / PSP','Description'=>'Mengelola hibah/PSP.'],['Code'=>'reports.view','Group'=>'Analitik','Label'=>'Lihat dan ekspor pelaporan','Description'=>'Menyusun dan mengekspor laporan.'],['Code'=>'search.view','Group'=>'Analitik','Label'=>'Pencarian detail barang','Description'=>'Mencari detail dan timeline.'],
        ['Code'=>'admin.users','Group'=>'Administrasi','Label'=>'Kelola pendaftaran pengguna','Description'=>'Menyetujui, menolak, menghapus, dan memberi role.'],['Code'=>'admin.roles','Group'=>'Administrasi','Label'=>'Kelola role & hak akses','Description'=>'Membuat dan mengubah role.'],['Code'=>'admin.parameters','Group'=>'Administrasi','Label'=>'Kelola parameter sistem','Description'=>'Mengelola master dropdown.'],
    ];
    public static function actionPermission(string $code): string {return ['pemindahan'=>'inventory.action.pemindahan','pindah_bongkar_kontainer'=>'inventory.action.bongkar_muat','pemberitahuan'=>'inventory.action.pemberitahuan','pencacahan'=>'inventory.action.pencacahan','request_penelitian_pfpd'=>'inventory.action.request_penelitian_pfpd','penelitian_pfpd'=>'inventory.action.penelitian_pfpd','penetapan_bmmn'=>'inventory.action.penetapan_bmmn','usulan_peruntukan_bmmn'=>'inventory.action.usulan_peruntukan_bmmn','persetujuan_peruntukan_bmmn'=>'inventory.action.persetujuan_peruntukan_bmmn','pengeluaran_barang'=>'inventory.action.pengeluaran_barang'][$code]??'';}
    public static function createPermission(string $type):string{return ['BTD'=>'inventory.create.btd','BDN'=>'inventory.create.bdn','TITIPAN'=>'inventory.create.titipan'][$type]??'';}
    public static function normalizePermissions(array $values):array{$valid=array_column(self::PERMISSIONS,'Code');$r=array_values(array_unique(array_intersect(array_map('trim',$values),$valid)));$deps=['dashboard.capacity.manage'=>['dashboard.view'],'inventory.create.btd'=>['inventory.view','inventory.type.btd'],'inventory.create.bdn'=>['inventory.view','inventory.type.bdn'],'inventory.create.titipan'=>['inventory.view','inventory.type.titipan'],'auction.manage'=>['auction.view'],'destruction.manage'=>['destruction.view'],'grant.manage'=>['grant.view'],'reconciliation.manage'=>['reconciliation.view']];foreach(self::INVENTORY_ACTIONS as $a)$deps[self::actionPermission($a['Code'])]=['inventory.view'];foreach($deps as $p=>$need)if(in_array($p,$r,true))foreach($need as $n)if(!in_array($n,$r,true))$r[]=$n;sort($r);return $r;}
    public static function actionsFor(string $type):array{return match($type){'lelang'=>self::AUCTION_ACTIONS,'musnah'=>self::DESTRUCTION_ACTIONS,'hibah'=>self::GRANT_ACTIONS,default=>[]};}
    public static function can(array $session,string $permission):bool{return ($session['Role']??'')==='admin'||in_array($permission,$session['Permissions']??[],true);}
    public static function allowedTypes(array $session):array{if(($session['Role']??'')==='admin')return self::TYPES;$map=['inventory.type.btd'=>'BTD','inventory.type.bdn'=>'BDN','inventory.type.bmmn'=>'BMMN','inventory.type.titipan'=>'TITIPAN'];$r=[];foreach($map as $p=>$t)if(self::can($session,$p))$r[]=$t;return $r;}
}
