<?php
declare(strict_types=1);
namespace Livira\Supabase;

use Livira\Domain\Domain;

/**
 * Local deterministic store for preview/smoke tests only. Production refuses DEMO_MODE.
 * The public API mirrors Store so controllers exercise the same PHP code paths.
 */
final class DemoStore
{
    private array $data=[];
    public function __construct(private readonly string $file,private readonly string $documentDir)
    {
        if(!is_dir(dirname($file)))@mkdir(dirname($file),0775,true);
        if(!is_dir($documentDir))@mkdir($documentDir,0775,true);
        $loaded=is_file($file)?json_decode((string)file_get_contents($file),true):null;
        $this->data=is_array($loaded)?$loaded:$this->seed();
        $this->save();
    }
    private function seed():array
    {
        $now=gmdate('c');$old=gmdate('c',strtotime('-70 days'));$mid=gmdate('c',strtotime('-28 days'));
        $facilities=[
            ['id'=>'tpp-transporindo','name'=>'TPP Transporindo','active'=>true,'sort_order'=>1,'yard_capacity'=>450,'yard_used'=>75,'shed_capacity'=>1200,'shed_used'=>210,'created_at'=>$old],
            ['id'=>'tpp-trikarya','name'=>'TPP Trikarya','active'=>true,'sort_order'=>2,'yard_capacity'=>320,'yard_used'=>38,'shed_capacity'=>900,'shed_used'=>160,'created_at'=>$old],
        ];
        $items=[
            $this->item('inv-btd-1','BTD','BTD-2026-001','ABCD1234567','40HC','FCL','Elektronik campuran',12,'KOLI',225000000,'tpp-transporindo','TPP Transporindo',$old,'ditetapkan','Ditetapkan sebagai BTD'),
            $this->item('inv-bdn-1','BDN','BDN-2026-014','EFGH7654321','20','FCL','Tekstil dan alas kaki',85,'KOLI',154000000,'tpp-trikarya','TPP Trikarya',$mid,'penelitian_pfpd','Penelitian PFPD'),
            $this->item('inv-bmmn-1','BMMN','KEP-BMMN-008','','','LCL','Peralatan kantor',24,'UNIT',78000000,'tpp-transporindo','TPP Transporindo',$mid,'bmmn_aktif','Ditetapkan sebagai BMMN'),
            $this->item('inv-tit-1','TITIPAN','TIT-2026-004','','','LCL','Barang titipan unit penindakan',6,'KOLI',0,'','',$now,'barang_titipan_aktif','Barang titipan aktif'),
        ];
        $events=[];foreach($items as $i)$events[]=['id'=>'evt-'.$i['id'],'inventory_id'=>$i['id'],'code'=>$i['status_code'],'label'=>$i['status_label'],'document_no'=>$i['determination_no'],'document_date'=>substr($i['determination_date'],0,10),'notes'=>'Data demo LIVIRA PHP','actor'=>'Administrator','created_at'=>$i['created_at'],'document_id'=>null];
        $roles=[['id'=>'role-operator','name'=>'Operator Inventory','description'=>'Input dan action inventory','permissions'=>Domain::normalizePermissions(['dashboard.view','inventory.view','inventory.create.btd','inventory.create.bdn','inventory.create.titipan','inventory.action.pemindahan','inventory.action.bongkar_muat','inventory.action.pencacahan','inventory.action.request_penelitian_pfpd','inventory.action.penelitian_pfpd','inventory.action.penetapan_bmmn','inventory.action.pengeluaran_barang','reports.view','search.view','reconciliation.view','reconciliation.manage','auction.view','auction.manage','destruction.view','destruction.manage','grant.view','grant.manage']),'active'=>true,'assigned_users'=>1,'created_at'=>$old]];
        $users=[['id'=>'user-demo','auth_user_id'=>'demo-user','name'=>'Petugas Demo','email'=>'petugas@example.test','email_verified'=>true,'approval_status'=>'approved','role_id'=>'role-operator','role_name'=>'Operator Inventory','permissions'=>$roles[0]['permissions'],'created_at'=>$old]];
        $parameters=[];$defs=['bdn_category'=>['Barang dilarang','Barang dibatasi'],'item_kind'=>['Barang Umum','Kendaraan','Mesin'],'goods_condition'=>['Baik','Rusak ringan','Rusak berat'],'unit'=>['KOLI','UNIT','SET','KG'],'allocation_purpose'=>['Lelang','Pemusnahan','Hibah','PSP'],'origin_tps'=>['TPS JICT','TPS KOJA'],'load_type'=>['FCL','LCL'],'exit_type'=>['lelang','musnah','hibah','psp'],'transfer_type'=>['hibah','psp'],'entrusted_category'=>['Penindakan','Kepabeanan']];
        foreach($defs as $group=>$labels)foreach($labels as $n=>$label)$parameters[]=['id'=>$group.'-'.$n,'group_code'=>$group,'code'=>strtolower(str_replace(' ','_',$label)),'label'=>$label,'applies_to'=>'','sort_order'=>$n+1,'active'=>true,'system'=>false,'created_at'=>$old];
        return ['facilities'=>$facilities,'items'=>$items,'events'=>$events,'dispositions'=>[],'users'=>$users,'roles'=>$roles,'parameters'=>$parameters,'reconciliations'=>[],'corrections'=>[],'documents'=>[]];
    }
    private function item(string $id,string $type,string $no,string $container,string $size,string $load,string $desc,float $qty,string $unit,int $value,string $fid,string $fname,string $date,string $status,string $label):array
    {
        $date=$date?:gmdate('c');return ['id'=>$id,'reference_no'=>$no,'item_type'=>$type,'origin_type'=>$type,'bl_no'=>'BL-'.$no,'bl_date'=>substr($date,0,10),'manifest_no'=>'MAN-'.$no,'manifest_date'=>substr($date,0,10),'manifest_position'=>'001','determination_no'=>$no,'determination_date'=>substr($date,0,10),'category'=>$type==='BDN'?'Barang dibatasi':'','entrusted_category'=>$type==='TITIPAN'?'Penindakan':'','source_office'=>$type==='TITIPAN'?'KPU BC Tanjung Priok':'','description'=>$desc,'item_kind'=>'Barang Umum','quantity'=>$qty,'quantity_detail'=>'','unit'=>$unit,'goods_value'=>$value,'goods_condition'=>'Baik','location'=>$fname?:'TPS JICT','location_status'=>$fname?:'TPS JICT','at_tpp'=>$fid!=='','owner_name'=>'Pemilik Demo','owner_address'=>'Jakarta','origin_warehouse'=>'TPS JICT','facility_id'=>$fid?:null,'facility_name'=>$fname,'load_type'=>$load,'container_no'=>$container,'container_size'=>$size,'estimated_volume_m3'=>$load==='LCL'?12.5:0,'physical_unit_id'=>$container!==''?preg_replace('/\W/','',$container):$id,'occupancy_primary'=>true,'pfpd_required'=>$type!=='TITIPAN','research_request_no'=>'','research_request_date'=>null,'hs_code'=>'','is_restricted'=>false,'restriction_rule'=>'','allocation_purpose'=>'','status_code'=>$status,'status_label'=>$label,'current_disposition'=>null,'is_active'=>true,'created_at'=>$date,'updated_at'=>$date,'created_by'=>'Administrator','search_text'=>strtolower($no.' '.$container.' '.$desc.' '.$fname)];
    }
    private function save():void{file_put_contents($this->file,(string)json_encode($this->data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);}
    private function id(string $prefix):string{return $prefix.'-'.bin2hex(random_bytes(8));}
    private function find(string $bucket,string $id):array{foreach($this->data[$bucket] as $row)if(($row['id']??'')===$id)return $row;throw new ApiException('Data tidak ditemukan.',404);}
    private function replace(string $bucket,array $row):void{foreach($this->data[$bucket] as $n=>$existing)if(($existing['id']??'')===($row['id']??'')){$this->data[$bucket][$n]=$row;$this->save();return;}$this->data[$bucket][]=$row;$this->save();}
    private function filterItems(array $f):array
    {
        $rows=$this->data['items'];$allowed=$f['allowed_types']??[];$q=mb_strtolower(trim((string)($f['query']??'')));
        $rows=array_values(array_filter($rows,function($i)use($f,$allowed,$q){
            if(!empty($f['only_inactive'])&&($i['is_active']??true))return false;if(empty($f['include_inactive'])&&empty($f['only_inactive'])&&!($i['is_active']??false))return false;
            if($allowed&&!in_array($i['item_type'],$allowed,true))return false;if(!empty($f['type'])&&$i['item_type']!==strtoupper((string)$f['type']))return false;
            if(!empty($f['facility_id'])&&($i['facility_id']??'')!==$f['facility_id'])return false;if(($f['location_scope']??'')==='tpp'&&empty($i['at_tpp']))return false;if(($f['location_scope']??'')==='tps'&&!empty($i['at_tpp']))return false;
            if(!empty($f['status'])&&($i['status_code']??'')!==$f['status'])return false;if(!empty($f['item_kind'])&&($i['item_kind']??'')!==$f['item_kind'])return false;if(!empty($f['goods_condition'])&&($i['goods_condition']??'')!==$f['goods_condition'])return false;
            if($q!==''&&!str_contains(mb_strtolower((string)($i['search_text']??implode(' ',array_filter($i,'is_scalar')))),$q))return false;return true;
        }));
        usort($rows,fn($a,$b)=>strcmp((string)($b['updated_at']??''),(string)($a['updated_at']??'')));
        $offset=max(0,(int)($f['offset']??0));$limit=(int)($f['limit']??0);return $limit>0?array_slice($rows,$offset,$limit):array_slice($rows,$offset);
    }
    public function facilities(bool $includeInactive=false):array{return array_values(array_filter($this->data['facilities'],fn($f)=>$includeInactive||!empty($f['active'])));}
    public function updateFacilityCapacity(string $id,float $yard,float $shed):array{$f=$this->find('facilities',$id);$f['yard_capacity']=max(0,$yard);$f['shed_capacity']=max(0,$shed);$this->replace('facilities',$f);return $f;}
    public function dashboard():array
    {
        $items=$this->filterItems(['include_inactive'=>false]);$types=['BTD'=>0,'BDN'=>0,'BMMN'=>0,'TITIPAN'=>0];foreach($items as $i)$types[$i['item_type']]++;
        $summary=fn(array $rows)=>['documents'=>count(array_unique(array_column($rows,'determination_no'))),'fcl'=>count(array_unique(array_filter(array_map(fn($i)=>$i['load_type']==='FCL'?$i['physical_unit_id']:null,$rows)))),'lcl'=>count(array_filter($rows,fn($i)=>$i['load_type']==='LCL'))];
        $facility=[];foreach($this->facilities() as $f){$row=['facility_id'=>$f['id'],'facility_name'=>$f['name'],'btd'=>0,'bdn'=>0,'bmmn'=>0,'titipan'=>0,'yard_used'=>$f['yard_used'],'yard_capacity'=>$f['yard_capacity'],'shed_used'=>$f['shed_used'],'shed_capacity'=>$f['shed_capacity']];foreach($items as $i)if(($i['facility_id']??'')===$f['id'])$row[strtolower($i['item_type'])]++;$row['total']=$row['btd']+$row['bdn']+$row['bmmn']+$row['titipan'];$facility[]=$row;}
        return ['active_total'=>count($items),'btd_total'=>$types['BTD'],'bdn_total'=>$types['BDN'],'bmmn_total'=>$types['BMMN'],'titipan_total'=>$types['TITIPAN'],'active_summary'=>$summary($items),'btd_summary'=>$summary(array_values(array_filter($items,fn($i)=>$i['item_type']==='BTD'))),'bdn_summary'=>$summary(array_values(array_filter($items,fn($i)=>$i['item_type']==='BDN'))),'bmmn_summary'=>$summary(array_values(array_filter($items,fn($i)=>$i['item_type']==='BMMN'))),'titipan_summary'=>$summary(array_values(array_filter($items,fn($i)=>$i['item_type']==='TITIPAN'))),'auction_active'=>count(array_filter($this->data['dispositions'],fn($p)=>$p['disposition_type']==='lelang'&&$p['is_active'])),'destruction_active'=>count(array_filter($this->data['dispositions'],fn($p)=>$p['disposition_type']==='musnah'&&$p['is_active'])),'grant_active'=>count(array_filter($this->data['dispositions'],fn($p)=>$p['disposition_type']==='hibah'&&$p['is_active'])),'facility_breakdown'=>$facility,'recent_events'=>array_slice(array_reverse($this->data['events']),0,8),'attention_items'=>array_slice(array_values(array_filter($items,fn($i)=>strtotime((string)$i['determination_date'])<strtotime('-45 days'))),0,8)];
    }
    public function listInventory(array $f=[]):array{return $this->filterItems($f);}
    public function countInventory(array $f=[]):int{unset($f['limit'],$f['offset']);return count($this->filterItems($f));}
    public function inventorySummary(array $f=[]):array{return ['total'=>$this->countInventory($f)];}
    public function getInventory(string $id):array{return $this->find('items',$id);}
    public function createInventories(array $inputs):array{$out=[];foreach($inputs as $in)$out[]=$this->createInventory($in);return$out;}
    public function createInventory(array $in):array
    {
        $type=strtoupper(trim((string)($in['type']??$in['item_type']??'')));if(!in_array($type,Domain::TYPES,true))throw new ApiException('Jenis inventory tidak valid.',422);$description=trim((string)($in['description']??''));$number=trim((string)($in['determination_no']??''));if($number===''||$description==='')throw new ApiException('Nomor dokumen dan uraian barang wajib diisi.',422);
        $id=$this->id('inv');$fid=trim((string)($in['facility_id']??''));$fname='';foreach($this->facilities() as $f)if($f['id']===$fid)$fname=$f['name'];$load=strtoupper(trim((string)($in['load_type']??'')))?:(!empty($in['container_no'])?'FCL':'LCL');$container=strtoupper((string)preg_replace('/[^A-Z0-9]/i','',(string)($in['container_no']??'')));$date=trim((string)($in['determination_date']??''))?:date('Y-m-d');
        $row=$this->item($id,$type,trim((string)($in['reference_no']??''))?:$number,$container,strtoupper((string)($in['container_size']??'')),$load,$description,(float)($in['quantity']??1),(string)($in['unit']??'KOLI'),(int)($in['goods_value']??0),$fid,$fname,$date.'T00:00:00Z',$type==='TITIPAN'?'barang_titipan_aktif':($fid!==''?'ditetapkan':'masih_di_tps'),$type==='TITIPAN'?'Barang titipan aktif':($fid!==''?'Ditetapkan sebagai '.$type:'Masih di TPS'));
        foreach($in as $k=>$v)if(array_key_exists($k,$row)&&$v!==''&&$v!==null&&!in_array($k,['container_no','load_type','container_size'],true))$row[$k]=$v;$row['container_no']=$container;$row['load_type']=$load;$row['container_size']=strtoupper((string)($in['container_size']??$row['container_size']));$row['created_by']=$in['actor']??'Administrator';$this->data['items'][]=$row;$this->data['events'][]=['id'=>$this->id('evt'),'inventory_id'=>$id,'code'=>$row['status_code'],'label'=>$row['status_label'],'document_no'=>$number,'document_date'=>$date,'notes'=>'Pencatatan awal','actor'=>$row['created_by'],'created_at'=>gmdate('c'),'document_id'=>$in['document_id']??null];$this->save();return$row;
    }
    public function deleteInventory(string $id,string $actor):void{$this->data['items']=array_values(array_filter($this->data['items'],fn($i)=>$i['id']!==$id));$this->data['events']=array_values(array_filter($this->data['events'],fn($e)=>($e['inventory_id']??'')!==$id));$this->save();}
    public function addInventoryEvent(string $id,array $in):array{$item=$this->getInventory($id);$code=(string)($in['code']??'');$label=$code===''?'Pembaruan':ucwords(str_replace('_',' ',$code));$item['status_code']=$code?:$item['status_code'];$item['status_label']=$label;$item['updated_at']=gmdate('c');if($code==='pemindahan'){foreach($this->facilities() as $f)if($f['id']===($in['target_facility_id']??'')){$item['facility_id']=$f['id'];$item['facility_name']=$f['name'];$item['at_tpp']=true;$item['location']=$f['name'];}}if($code==='pengeluaran_barang')$item['is_active']=false;if($code==='penetapan_bmmn')$item['item_type']='BMMN';foreach(['description','item_kind','quantity','unit','goods_condition','goods_value','hs_code','restriction_rule','allocation_purpose','exit_type'] as $k)if(array_key_exists($k,$in)&&$in[$k]!=='')$item[$k]=$in[$k];$this->replace('items',$item);$event=['id'=>$this->id('evt'),'inventory_id'=>$id,'code'=>$code,'label'=>$label,'document_no'=>$in['document_no']??'','document_date'=>$in['document_date']??date('Y-m-d'),'notes'=>$in['notes']??'','actor'=>$in['actor']??'Administrator','created_at'=>gmdate('c'),'document_id'=>$in['document_id']??null];$this->data['events'][]=$event;$this->save();return['item'=>$item,'event'=>$event];}
    public function applyCensus(string $id,array $lines,array $in):array{$out=[];foreach($lines as $line){$line['code']='pencacahan';$line+=$in;$out[]=$this->addInventoryEvent((string)($line['inventory_id']??$id),$line)['item'];}return$out;}
    public function relocateLoad(string $id,array $allocations,array $in):array{$out=[];foreach($allocations as $a){$target=(string)($a['inventory_id']??$id);$item=$this->getInventory($target);foreach(['load_type','container_no','container_size','estimated_volume_m3','physical_unit_id','occupancy_primary'] as $k)if(array_key_exists($k,$a))$item[$k]=$a[$k];$item['updated_at']=gmdate('c');$this->replace('items',$item);$out[]=$item;}$in['code']='pindah_bongkar_kontainer';$this->addInventoryEvent($id,$in);return$out;}
    public function timeline(string $id):array{return array_values(array_filter($this->data['events'],fn($e)=>($e['inventory_id']??'')===$id));}
    public function processTimeline(string $id):array{return array_values(array_filter($this->data['events'],fn($e)=>($e['disposition_id']??'')===$id));}
    public function listEvents(int $limit=50000):array{return array_slice($this->data['events'],-$limit);}
    public function listDispositions(array $f=[]):array{$rows=$this->data['dispositions'];$rows=array_values(array_filter($rows,function($p)use($f){if(!empty($f['type'])&&$p['disposition_type']!==$f['type'])return false;if(empty($f['include_inactive_inventory'])&&isset($p['inventory_is_active'])&&!$p['inventory_is_active'])return false;if(!empty($f['status'])&&$p['status_code']!==$f['status'])return false;return true;}));$offset=(int)($f['offset']??0);$limit=(int)($f['limit']??0);return$limit?array_slice($rows,$offset,$limit):array_slice($rows,$offset);}
    public function countDispositions(array $f=[]):int{unset($f['limit'],$f['offset']);return count($this->listDispositions($f));}
    public function processDashboard(string $type,int $year,array $allowed):array{$rows=$this->listDispositions(['type'=>$type,'include_inactive_inventory'=>true]);return['year'=>$year,'total'=>count($rows),'active'=>count(array_filter($rows,fn($r)=>!empty($r['is_active']))),'closed'=>count(array_filter($rows,fn($r)=>empty($r['is_active']))),'rows'=>$rows];}
    public function getDisposition(string $id):array{return$this->find('dispositions',$id);}
    public function createDisposition(string $inventoryId,string $type,string $actor,string $notes=''):array{$item=$this->getInventory($inventoryId);$row=['id'=>$this->id('proc'),'inventory_id'=>$inventoryId,'disposition_type'=>$type,'status_code'=>$type==='lelang'?'kep_lelang':($type==='musnah'?'kep_musnah':'ba_serah_terima'),'status_label'=>ucfirst($type).' dimulai','round'=>1,'is_active'=>true,'inventory_reference_no'=>$item['reference_no'],'inventory_type'=>$item['item_type'],'inventory_description'=>$item['description'],'inventory_goods_value'=>$item['goods_value'],'inventory_facility_id'=>$item['facility_id'],'inventory_facility_name'=>$item['facility_name'],'inventory_is_active'=>$item['is_active'],'updated_at'=>gmdate('c'),'created_at'=>gmdate('c')];$this->data['dispositions'][]=$row;foreach($this->data['items'] as &$i)if($i['id']===$inventoryId)$i['current_disposition']=$type;unset($i);$this->save();return$row;}
    public function addDispositionEvent(string $id,array $in):array{$p=$this->getDisposition($id);$code=(string)($in['code']??'');$status=$code;$label=ucwords(str_replace('_',' ',$code));if($code==='selesai_lelang'){$status=(string)($in['auction_outcome']??'tidak_laku');$label=$status==='laku'?'Laku':'Tidak laku';}$p['status_code']=$status;$p['status_label']=$label;$p['updated_at']=gmdate('c');if(in_array($code,['alokasi_hasil_lelang','ba_musnah','ba_serah_terima'],true))$p['is_active']=false;foreach(['sale_value','htl_value','destruction_cost','auction_outcome','transfer_type','allocation_target','execution_start_date','execution_end_date'] as $k)if(array_key_exists($k,$in))$p[$k]=$in[$k];$this->replace('dispositions',$p);$event=['id'=>$this->id('evt'),'inventory_id'=>$p['inventory_id'],'disposition_id'=>$id,'disposition_type'=>$p['disposition_type'],'code'=>$code,'label'=>$label,'document_no'=>$in['document_no']??'','document_date'=>$in['document_date']??date('Y-m-d'),'notes'=>$in['notes']??'','actor'=>$in['actor']??'Administrator','created_at'=>gmdate('c'),'document_id'=>$in['document_id']??null];$this->data['events'][]=$event;$this->save();return['process'=>$p,'event'=>$event];}
    public function createUserApplication(string $authId,string $name,string $email):array{$u=['id'=>$this->id('user'),'auth_user_id'=>$authId,'name'=>$name,'email'=>$email,'email_verified'=>false,'approval_status'=>'pending','role_id'=>null,'role_name'=>'','permissions'=>[],'created_at'=>gmdate('c')];$this->data['users'][]=$u;$this->save();return$u;}
    public function markUserEmailVerified(string $authId,string $email):void{foreach($this->data['users'] as &$u)if($u['auth_user_id']===$authId||$u['email']===$email){$u['email_verified']=true;$u['email_verified_at']=gmdate('c');}unset($u);$this->save();}
    public function userByAuthId(string $authId):array{foreach($this->data['users'] as $u)if($u['auth_user_id']===$authId)return$u;throw new ApiException('Pengguna belum terdaftar.',404);}
    public function listUsers():array{return$this->data['users'];}
    public function approveUser(string $id,string $roleId,string $actor):void{foreach($this->data['users'] as &$u)if($u['id']===$id){$r=$this->find('roles',$roleId);$u['approval_status']='approved';$u['role_id']=$roleId;$u['role_name']=$r['name'];$u['permissions']=$r['permissions'];}unset($u);$this->save();}
    public function rejectUser(string $id,string $reason,string $actor):void{foreach($this->data['users'] as &$u)if($u['id']===$id){$u['approval_status']='rejected';$u['rejection_reason']=$reason;}unset($u);$this->save();}
    public function updateUserRole(string $id,string $roleId,string $actor):void{$this->approveUser($id,$roleId,$actor);}
    public function deleteUser(string $id):array{$u=$this->find('users',$id);$this->data['users']=array_values(array_filter($this->data['users'],fn($x)=>$x['id']!==$id));$this->save();return$u;}
    public function listRoles(bool $includeInactive=true):array{$r=$this->data['roles'];foreach($r as &$role)$role['assigned_users']=count(array_filter($this->data['users'],fn($u)=>($u['role_id']??'')===$role['id']));unset($role);return array_values(array_filter($r,fn($x)=>$includeInactive||!empty($x['active'])));}
    public function createRole(array $in):array{$r=['id'=>$this->id('role'),'name'=>trim((string)$in['name']),'description'=>trim((string)($in['description']??'')),'permissions'=>Domain::normalizePermissions((array)($in['permissions']??[])),'active'=>true,'assigned_users'=>0,'created_at'=>gmdate('c')];$this->data['roles'][]=$r;$this->save();return$r;}
    public function updateRole(string $id,array $in):array{$r=$this->find('roles',$id);$r['name']=trim((string)$in['name']);$r['description']=trim((string)($in['description']??''));$r['permissions']=Domain::normalizePermissions((array)($in['permissions']??[]));$this->replace('roles',$r);return$r;}
    public function setRoleActive(string $id,bool $active):void{$r=$this->find('roles',$id);$r['active']=$active;$this->replace('roles',$r);}
    public function deleteRole(string $id):array{$r=$this->find('roles',$id);if(count(array_filter($this->data['users'],fn($u)=>($u['role_id']??'')===$id))>0)throw new ApiException('Role masih digunakan oleh pengguna.',409);$this->data['roles']=array_values(array_filter($this->data['roles'],fn($x)=>$x['id']!==$id));$this->save();return$r;}
    public function parameterOptions(string $group='',bool $includeInactive=true):array{$p=array_values(array_filter($this->data['parameters'],fn($x)=>($group===''||$x['group_code']===$group)&&($includeInactive||!empty($x['active']))));if($group===''||$group==='tpp')foreach($this->facilities($includeInactive) as $f)$p[]=['id'=>'facility--'.$f['id'],'group_code'=>'tpp','code'=>$f['id'],'label'=>$f['name'],'active'=>$f['active'],'system'=>true,'sort_order'=>$f['sort_order'],'created_at'=>$f['created_at']];return$p;}
    public function createParameter(array $in):array{$group=(string)$in['group_code'];if($group==='tpp'){$f=['id'=>strtolower(preg_replace('/[^a-z0-9]+/i','-',(string)($in['code']??$in['label']))),'name'=>(string)$in['label'],'active'=>true,'sort_order'=>(int)($in['sort_order']??999),'yard_capacity'=>0,'yard_used'=>0,'shed_capacity'=>0,'shed_used'=>0,'created_at'=>gmdate('c')];$this->data['facilities'][]=$f;$this->save();return$f;}$p=['id'=>$this->id('param'),'group_code'=>$group,'code'=>strtolower(preg_replace('/[^a-z0-9]+/i','_',(string)($in['code']??$in['label']))),'label'=>(string)$in['label'],'applies_to'=>implode(',',(array)($in['applies_to']??[])),'sort_order'=>(int)($in['sort_order']??999),'active'=>true,'system'=>false,'created_at'=>gmdate('c')];$this->data['parameters'][]=$p;$this->save();return$p;}
    public function updateParameter(string $id,array $in):array{if(str_starts_with($id,'facility--')){$f=$this->find('facilities',substr($id,10));$f['name']=(string)$in['label'];$f['sort_order']=(int)($in['sort_order']??$f['sort_order']);$this->replace('facilities',$f);return$f;}$p=$this->find('parameters',$id);$p['label']=(string)$in['label'];$p['sort_order']=(int)($in['sort_order']??$p['sort_order']);$p['applies_to']=implode(',',(array)($in['applies_to']??[]));$this->replace('parameters',$p);return$p;}
    public function setParameterActive(string $id,bool $active):void{if(str_starts_with($id,'facility--')){$f=$this->find('facilities',substr($id,10));$f['active']=$active;$this->replace('facilities',$f);}else{$p=$this->find('parameters',$id);$p['active']=$active;$this->replace('parameters',$p);}}
    public function createDocument(array $file,string $actor):array{$content=(string)file_get_contents((string)$file['tmp_name']);$id=$this->id('doc');$name=basename((string)$file['name']);$path=$id.'-'.preg_replace('/[^A-Za-z0-9._-]/','_',$name);file_put_contents($this->documentDir.'/'.$path,$content);$d=['id'=>$id,'file_name'=>$name,'mime_type'=>$file['type']??'application/octet-stream','size_bytes'=>strlen($content),'uploaded_by'=>$actor,'storage_bucket'=>'demo','storage_path'=>$path,'sha256'=>hash('sha256',$content),'created_at'=>gmdate('c')];$this->data['documents'][]=$d;$this->save();return$d;}
    public function getDocument(string $id):array{$d=$this->find('documents',$id);$content=(string)file_get_contents($this->documentDir.'/'.$d['storage_path']);return[$d,$content];}
    public function documentAccess(string $id):array{$out=[];foreach($this->data['events'] as $event){if(($event['document_id']??'')!==$id)continue;try{$item=$this->getInventory((string)($event['inventory_id']??''));$out[]=['inventory'=>$item,'disposition_type'=>$event['disposition_type']??'','event_code'=>$event['code']??''];}catch(\Throwable){}}if(!$out)throw new ApiException('Dokumen tidak ditemukan.',404);return$out;}
    public function notifications(array $allowed):array{return['count'=>0,'items'=>[]];}
    public function audit(array $e):void{}
    public function listReconciliations(int $limit=5000):array{return array_slice(array_reverse($this->data['reconciliations']),0,$limit);}
    public function reconcile(array $in):array{if(($in['type']??'')==='found_not_recorded'){$item=$this->createInventory(($in['new_item']??[])+['actor'=>$in['actor']??'Administrator']);$r=['id'=>$this->id('rec'),'reconciliation_type'=>'found_not_recorded','action'=>'added','inventory_id'=>$item['id'],'inventory_reference'=>$item['reference_no'],'inventory_type'=>$item['item_type'],'result_status_code'=>$item['status_code'],'result_status_label'=>$item['status_label'],'notes'=>$in['notes']??'','actor'=>$in['actor']??'Administrator','created_at'=>gmdate('c')];}else{$item=$this->getInventory((string)$in['inventory_id']);$item['is_active']=false;$item['status_code']='rekonsiliasi_tidak_ditemukan';$item['status_label']='Tidak ditemukan di lapangan';$this->replace('items',$item);$r=['id'=>$this->id('rec'),'reconciliation_type'=>'recorded_not_found','action'=>'removed','inventory_id'=>$item['id'],'inventory_reference'=>$item['reference_no'],'inventory_type'=>$item['item_type'],'result_status_code'=>$item['status_code'],'result_status_label'=>$item['status_label'],'notes'=>$in['notes']??'','actor'=>$in['actor']??'Administrator','created_at'=>gmdate('c')];}$this->data['reconciliations'][]=$r;$this->save();return[$r,$item];}
    public function correctInventory(array $payload):array
    {
        $item=$this->getInventory((string)($payload['p_inventory_id']??''));
        $changes=(array)($payload['p_changes']??[]);$details=[];
        foreach($changes as $key=>$value){
            $before=$item[$key]??null;
            if($before==$value)continue;
            $details[]=['section'=>'inventory','entity_id'=>$item['id'],'context'=>'Data utama barang','field'=>$key,'before'=>(string)($before??''),'after'=>(string)($value??'')];
            $item[$key]=$value;
        }
        if(!$details)throw new ApiException('Tidak ada perubahan data yang terdeteksi.',422);
        $item['updated_at']=gmdate('c');$this->replace('items',$item);
        $record=['id'=>$this->id('rec'),'reconciliation_type'=>'data_correction','action'=>'corrected','inventory_id'=>$item['id'],'inventory_reference'=>$item['reference_no'],'inventory_type'=>$item['item_type'],'previous_status_code'=>$item['status_code'],'previous_status_label'=>$item['status_label'],'result_status_code'=>$item['status_code'],'result_status_label'=>$item['status_label'],'correction_reason'=>$payload['p_reason']??'','change_details'=>$details,'notes'=>'Perubahan data barang','actor'=>$payload['p_actor']??'Administrator','created_at'=>gmdate('c')];
        $this->data['reconciliations'][]=$record;$this->save();return['inventory'=>$item,'reconciliation'=>$record];
    }
    public function listCorrections(int $limit=5000):array{return array_slice(array_values(array_filter(array_reverse($this->data['reconciliations']),fn($r)=>($r['reconciliation_type']??'')==='data_correction')),0,$limit);}
}
