<?php
declare(strict_types=1);
namespace Livira\Supabase;

use Livira\Config;
use Livira\Domain\Domain;

final class Store
{
    public function __construct(private readonly Config $config, private readonly SupabaseClient $db) {}
    private function now():string{return gmdate('c');}
    private function rows(mixed $v):array{return is_array($v)?$v:[];}
    private function first(mixed $v,string $message='Data tidak ditemukan'):array{$r=$this->rows($v);if(!$r)throw new ApiException($message,404);return $r[0];}
    public function facilities(bool $includeInactive=false):array{$q=['select'=>'id,name,active,sort_order,yard_capacity,yard_used,shed_capacity,shed_used,created_at','order'=>'sort_order.asc,name.asc','limit'=>'1000'];if(!$includeInactive)$q['active']='eq.true';return $this->rows($this->db->rest('GET','facilities',$q));}
    public function updateFacilityCapacity(string $id,float $yard,float $shed):array{if($id===''||$yard<0||$shed<0)throw new ApiException('Kapasitas tidak valid.',422);return $this->first($this->db->rest('PATCH','facilities',['id'=>'eq.'.$id,'active'=>'eq.true','select'=>'*'],['yard_capacity'=>$yard,'shed_capacity'=>$shed]));}
    public function dashboard():array
    {
        $s=(array)$this->db->rest('POST','rpc/livira_dashboard_summary',[],new \stdClass());
        $active=(int)($s['active_total']??0);$sum=(int)($s['btd_total']??0)+(int)($s['bdn_total']??0)+(int)($s['bmmn_total']??0)+(int)($s['titipan_total']??0);
        if($active!==$sum){$tit=$this->listInventory(['type'=>'TITIPAN','limit'=>50000]);$s['titipan_total']=count($tit);$s['titipan_summary']=$this->summarizeDashboard($tit);}
        $s['active_total']=(int)($s['btd_total']??0)+(int)($s['bdn_total']??0)+(int)($s['bmmn_total']??0)+(int)($s['titipan_total']??0);
        foreach($s['facility_breakdown']??[] as &$row){$row['total']=(int)($row['btd']??0)+(int)($row['bdn']??0)+(int)($row['bmmn']??0)+(int)($row['titipan']??0);}unset($row);
        return $s;
    }
    private function summarizeDashboard(array $items):array{$docs=[];$fcl=[];$lcl=[];foreach($items as $i){$docs[$i['determination_no']??$i['reference_no']??uniqid()]=1;if(strtoupper((string)($i['load_type']??''))==='FCL')$fcl[$i['physical_unit_id']??$i['container_no']??$i['id']]=1;else$lcl[$i['physical_unit_id']??$i['id']]=1;}return ['documents'=>count($docs),'fcl'=>count($fcl),'lcl'=>count($lcl)];}

    public function inventoryQuery(array $f):array
    {
        $q=['select'=>'*'];if(!empty($f['only_inactive']))$q['is_active']='eq.false';elseif(empty($f['include_inactive']))$q['is_active']='eq.true';
        if($v=$this->date($f['date_from']??''))$q['determination_date'][]='gte.'.$v;if($v=$this->date($f['date_to']??''))$q['determination_date'][]='lt.'.date('Y-m-d',strtotime($v.' +1 day'));if($v=$this->date($f['age_before']??''))$q['determination_date'][]='lt.'.date('Y-m-d',strtotime($v.' +1 day'));
        if(!empty($f['facility_id']))$q['facility_id']='eq.'.$f['facility_id'];$allowed=$f['allowed_types']??[];$type=strtoupper((string)($f['type']??''));if($type!==''){if($allowed&&!in_array($type,$allowed,true))return ['__invalid'=>true];$q['item_type']='eq.'.$type;}elseif($allowed)$q['item_type']='in.('.implode(',',$allowed).')';
        foreach(['status'=>'status_code','item_kind'=>'item_kind','goods_condition'=>'goods_condition','category'=>'category'] as $in=>$col)if(!empty($f[$in]))$q[$col]='eq.'.$f[$in];if(!empty($f['allocation_purpose']))$q['allocation_purpose']='ilike.'.$f['allocation_purpose'];if(($f['location_scope']??'')==='tpp')$q['at_tpp']='eq.true';elseif(($f['location_scope']??'')==='tps')$q['at_tpp']='eq.false';if((int)($f['min_value']??0)>0)$q['goods_value'][]='gte.'.(int)$f['min_value'];if((int)($f['max_value']??0)>0)$q['goods_value'][]='lte.'.(int)$f['max_value'];
        switch($f['preset']??''){case'overdue_60':$q['item_type']=$type!==''?'eq.'.$type:'in.(BTD,BDN)';$q['status_code']=!empty($f['status'])?'eq.'.$f['status']:'in.(masih_di_tps,ditetapkan)';break;case'auction_ready':$q['current_disposition']='is.null';if((int)($f['min_value']??0)<=0)$q['goods_value']='gt.0';$q['or']='(status_code.eq.penelitian_pfpd,item_type.eq.BMMN)';break;case'bmmn_allocation':$q['item_type']='eq.BMMN';$q['current_disposition']='is.null';break;}
        if(trim((string)($f['query']??''))!==''){$term=preg_replace('/[^\pL\pN\s\-_\/\.\'\(\)]/u','',trim((string)$f['query']));if($term==='')return ['__invalid'=>true];$q['search_text']='ilike.*'.$term.'*';}
        $q['order']=match($f['sort']??'newest'){'oldest','determination_oldest'=>'determination_date.asc','determination_newest'=>'determination_date.desc','container_asc'=>'container_no.asc','container_desc'=>'container_no.desc','tpp'=>'facility_name.asc,updated_at.desc','value_desc'=>'goods_value.desc,updated_at.desc','value_asc'=>'goods_value.asc,updated_at.desc',default=>'updated_at.desc'};
        if((int)($f['offset']??0)>0)$q['offset']=(string)(int)$f['offset'];if((int)($f['limit']??0)>0)$q['limit']=(string)(int)$f['limit'];return $q;
    }
    public function listInventory(array $f=[]):array{$q=$this->inventoryQuery($f);if(isset($q['__invalid']))return[];return $this->rows($this->db->rest('GET','inventory_items',$q));}
    public function countInventory(array $f=[]):int{$q=$this->inventoryQuery($f);if(isset($q['__invalid']))return 0;unset($q['order'],$q['offset'],$q['limit']);return $this->db->restCount('inventory_items',$q);}
    public function inventorySummary(array $f=[]):array{$types=$f['allowed_types']??[];return (array)$this->db->rest('POST','rpc/livira_inventory_summary',[],['p_filter'=>$this->inventoryQuery($f),'p_types'=>$types]);}
    public function getInventory(string $id):array{return $this->first($this->db->rest('GET','inventory_items',['select'=>'*','id'=>'eq.'.$id,'limit'=>'1']));}
    public function createInventories(array $inputs):array
    {
        if(!$inputs)throw new ApiException('Tidak ada barang yang akan disimpan.',422);$facilities=$this->facilities();$names=[];foreach($facilities as $f)$names[$f['id']]=$f['name'];$payloads=[];$refs=[];$containerUnits=[];
        foreach($inputs as $idx=>$in){$type=strtoupper(trim((string)($in['type']??'')));$load=strtoupper(trim((string)($in['load_type']??'')));$container=$this->normalizeContainer((string)($in['container_no']??''),true);if($load==='')$load=$container===''?'LCL':'FCL';$determination=trim((string)($in['determination_no']??''));$ref=trim((string)($in['reference_no']??''))?:$determination.(count($inputs)>1?'/'.str_pad((string)($idx+1),2,'0',STR_PAD_LEFT):'');if($determination===''||trim((string)($in['description']??''))===''||(float)($in['quantity']??0)<=0||!in_array($type,Domain::TYPES,true))throw new ApiException('Data inventory belum lengkap atau tidak valid.',422);if(isset($refs[$ref]))throw new ApiException('Nomor referensi ganda pada satu penyimpanan.',409);$refs[$ref]=1;
            $at=$this->bool($in['at_tpp']??false);$facilityId=$at?trim((string)($in['facility_id']??'')):'';$facilityName=$facilityId!==''?($names[$facilityId]??''):'';if($at&&$facilityName==='')throw new ApiException('TPP tujuan tidak valid.',422);$origin=trim((string)($in['origin_warehouse']??''));$source=trim((string)($in['source_office']??''));$location=trim((string)($in['location']??''));$status='masih_di_tps';$label='Masih di TPS';$locStatus=$origin;if($type==='TITIPAN'){$status='barang_titipan_aktif';$label='Barang titipan aktif';$locStatus=$source;$location=$location?:$source;}if($at){$status=$type==='TITIPAN'?'barang_titipan_aktif':'ditetapkan';$label=$type==='TITIPAN'?'Barang titipan aktif':'Ditetapkan sebagai '.$type;$locStatus=$facilityName;$location=$location?:$facilityName;}else{$location=$location?:($type==='TITIPAN'?$source:$origin);}if(!empty($in['initial_status_code'])){$status=trim((string)$in['initial_status_code']);$label=trim((string)($in['initial_status_label']??$status));}
            $unit=trim((string)($in['physical_unit_id']??''))?:$ref;$primary=array_key_exists('occupancy_primary',$in)?$this->bool($in['occupancy_primary']):true;$size=strtoupper(trim((string)($in['container_size']??'')));if($size==='45')$size='45HC';$volume=(float)($in['estimated_volume_m3']??0);if($load==='FCL'){if($container===''||!in_array($size,['20','40','40HC','45HC'],true))throw new ApiException('Nomor/ukuran kontainer FCL tidak valid.',422);$volume=0;$compact=preg_replace('/\D/','',$container);if(isset($containerUnits[$container])&&$containerUnits[$container]!==$unit)throw new ApiException('Kontainer yang sama memiliki unit fisik berbeda.',409);$containerUnits[$container]=$unit;}elseif($load==='LCL'){if($volume<=0)$volume=(float)($in['quantity']??0);$container='';$size='';}else throw new ApiException('Jenis muatan harus FCL atau LCL.',422);
            $row=['reference_no'=>$ref,'item_type'=>$type,'origin_type'=>$type,'bl_no'=>trim((string)($in['bl_no']??'')),'bl_date'=>$this->nullableDate($in['bl_date']??''),'manifest_no'=>trim((string)($in['manifest_no']??'')),'manifest_date'=>$this->nullableDate($in['manifest_date']??''),'manifest_position'=>trim((string)($in['manifest_position']??'')),'determination_no'=>$determination,'determination_date'=>$this->nullableDate($in['determination_date']??'')?:$this->now(),'category'=>trim((string)($in['category']??'')),'entrusted_category'=>trim((string)($in['entrusted_category']??'')),'source_office'=>$source,'description'=>trim((string)$in['description']),'item_kind'=>trim((string)($in['item_kind']??'')),'quantity'=>(float)$in['quantity'],'quantity_detail'=>trim((string)($in['quantity_detail']??'')),'unit'=>trim((string)($in['unit']??'')),'goods_value'=>(int)($in['goods_value']??0),'goods_condition'=>trim((string)($in['goods_condition']??'')),'location'=>$location,'location_status'=>$locStatus,'at_tpp'=>$at,'owner_name'=>trim((string)($in['owner_name']??'')),'owner_address'=>trim((string)($in['owner_address']??'')),'origin_warehouse'=>$origin,'facility_id'=>$facilityId?:null,'facility_name'=>$facilityName,'load_type'=>$load,'container_no'=>$container,'container_size'=>$size,'estimated_volume_m3'=>$volume,'physical_unit_id'=>$unit,'occupancy_primary'=>$primary,'pfpd_required'=>$this->bool($in['pfpd_required']??($type!=='TITIPAN')),'restriction_rule'=>trim((string)($in['restriction_rule']??'')),'status_code'=>$status,'status_label'=>$label,'is_active'=>true,'created_by'=>trim((string)($in['actor']??'')),'_initial_disposition_type'=>(string)($in['initial_disposition_type']??''),'_initial_transfer_type'=>(string)($in['initial_transfer_type']??''),'_initial_status_code'=>(string)($in['initial_status_code']??''),'_reconciliation_created'=>$this->bool($in['reconciliation_created']??false),'_document_id'=>trim((string)($in['document_id']??''))];$payloads[]=$row;
        }
        return $this->rows($this->db->rest('POST','rpc/livira_create_inventories',[],['p_rows'=>$payloads]));
    }
    public function createInventory(array $in):array{return $this->first($this->createInventories([$in]));}
    public function deleteInventory(string $id,string $actor):void{$this->db->rest('POST','rpc/admin_delete_inventory',[],['p_inventory_id'=>$id,'p_deleted_by'=>$actor]);}

    public function addInventoryEvent(string $id,array $in):array
    {
        $item=$this->getInventory($id);if(empty($item['is_active']))throw new ApiException('Barang sudah tidak aktif.',409);$code=trim((string)($in['code']??''));$actions=[];foreach(Domain::INVENTORY_ACTIONS as $a)$actions[$a['Code']]=$a;if(!isset($actions[$code]))throw new ApiException('Action inventory tidak valid.',422);$doc=trim((string)($in['document_no']??''));$date=$this->nullableDate($in['document_date']??'');if($doc===''||$date===null)throw new ApiException('Nomor dan tanggal dokumen wajib diisi.',422);$label=$actions[$code]['Label'];$patch=['status_code'=>$code,'status_label'=>$label];
        if($code==='pemindahan'){$fac=$this->first(array_values(array_filter($this->facilities(),fn($f)=>($f['id']??'')===($in['target_facility_id']??''))),'TPP tujuan tidak ditemukan.');$patch+=['at_tpp'=>true,'facility_id'=>$fac['id'],'facility_name'=>$fac['name'],'location'=>$fac['name'],'location_status'=>$fac['name']];}
        elseif($code==='pencacahan'){$patch+=['description'=>trim((string)($in['description']??'')),'item_kind'=>trim((string)($in['item_kind']??'')),'quantity'=>(float)($in['quantity']??0),'unit'=>trim((string)($in['unit']??'')),'goods_condition'=>trim((string)($in['goods_condition']??'')),'pfpd_required'=>true,'research_request_no'=>'','research_request_date'=>null,'hs_code'=>'','is_restricted'=>false,'restriction_rule'=>''];}
        elseif($code==='request_penelitian_pfpd'){$patch+=['research_request_no'=>$doc,'research_request_date'=>$date];}
        elseif($code==='penelitian_pfpd'){$restricted=(string)($in['restriction_status']??'')==='ya';$patch+=['hs_code'=>trim((string)($in['hs_code']??'')),'is_restricted'=>$restricted,'restriction_rule'=>trim((string)($in['restriction_rule']??'')),'goods_value'=>(int)($in['goods_value']??0)];}
        elseif($code==='penetapan_bmmn'){$patch+=['origin_document_type'=>'Penetapan '.($item['item_type']??''),'origin_document_no'=>$item['determination_no']??'','origin_document_date'=>$item['determination_date']??null,'determination_no'=>$doc,'determination_date'=>$date,'item_type'=>'BMMN','status_code'=>'bmmn_aktif','status_label'=>'Ditetapkan sebagai BMMN'];}
        elseif($code==='usulan_peruntukan_bmmn'){$allocation=trim((string)($in['allocation_type']??''));$patch+=['allocation_proposal_type'=>$allocation,'allocation_proposal_no'=>$doc,'allocation_proposal_date'=>$date,'allocation_purpose'=>$allocation];}
        elseif($code==='persetujuan_peruntukan_bmmn'){$allocation=trim((string)($in['allocation_type']??''));$patch+=['allocation_approval_type'=>$allocation,'allocation_approval_no'=>$doc,'allocation_approval_date'=>$date,'allocation_purpose'=>$allocation];}
        elseif($code==='pengeluaran_barang'){$patch+=['exit_document_no'=>$doc,'exit_document_date'=>$date,'exit_type'=>trim((string)($in['exit_type']??'')),'exit_notes'=>trim((string)($in['exit_notes']??'')),'is_active'=>false,'location_status'=>'Barang telah dikeluarkan','status_code'=>'pengeluaran_barang','status_label'=>'Pengeluaran barang selesai'];if(!(($in['exit_type']??'')==='musnah'&&($item['current_disposition']??'')==='musnah'))$patch['current_disposition']=null;}
        $event=['code'=>$code,'label'=>$patch['status_label'],'document_no'=>$doc,'document_date'=>$date,'notes'=>trim((string)($in['notes']??'')),'actor'=>trim((string)($in['actor']??'')),'document_id'=>$this->nullString($in['document_id']??'')];$payload=['p_inventory_id'=>$id,'p_expected_updated_at'=>$item['updated_at']??null,'p_item_patch'=>$patch,'p_close_active_dispositions'=>$code==='pengeluaran_barang','p_keep_destruction_open'=>$code==='pengeluaran_barang'&&($in['exit_type']??'')==='musnah'&&($item['current_disposition']??'')==='musnah','p_event'=>$event];return (array)$this->db->rest('POST','rpc/livira_apply_inventory_event',[],$payload);
    }
    public function applyCensus(string $id,array $lines,array $in):array
    {
        $item=$this->getInventory($id);$group=trim((string)($item['physical_unit_id']??''))?:$id;$payload=['p_inventory_id'=>$id,'p_expected_updated_at'=>$item['updated_at']??null,'p_lines'=>$lines,'p_event'=>['code'=>'pencacahan','label'=>'Pencacahan','document_no'=>trim((string)($in['document_no']??'')),'document_date'=>$this->nullableDate($in['document_date']??''),'notes'=>trim((string)($in['notes']??'')),'actor'=>trim((string)($in['actor']??'')),'document_id'=>$this->nullString($in['document_id']??'')],'p_physical_unit_id'=>$group];
        try{return $this->rows($this->db->rest('POST','rpc/livira_apply_inventory_census',[],$payload));}catch(ApiException){
            // Compatibility implementation for databases before the dedicated census RPC.
            $updated=[];foreach($lines as $line){$lineId=trim((string)($line['inventory_id']??''));if($lineId==='')continue;$patch=['description'=>trim((string)($line['description']??'')),'item_kind'=>trim((string)($line['item_kind']??'')),'goods_value'=>(int)($line['goods_value']??0),'quantity'=>(float)($line['quantity']??0),'quantity_detail'=>trim((string)($line['quantity_detail']??'')),'unit'=>trim((string)($line['unit']??'')),'goods_condition'=>trim((string)($line['goods_condition']??'')),'physical_unit_id'=>$group,'pfpd_required'=>true,'status_code'=>'pencacahan','status_label'=>'Pencacahan','updated_at'=>$this->now()];$updated[]=$this->first($this->db->rest('PATCH','inventory_items',['id'=>'eq.'.$lineId,'select'=>'*'],$patch));}return $updated;
        }
    }
    public function relocateLoad(string $id,array $allocations,array $in):array{$item=$this->getInventory($id);$payload=['p_inventory_id'=>$id,'p_expected_updated_at'=>$item['updated_at']??null,'p_allocations'=>$allocations,'p_event'=>['code'=>'pindah_bongkar_kontainer','label'=>'Bongkar/Muat Kontainer','document_no'=>trim((string)($in['document_no']??'')),'document_date'=>$this->nullableDate($in['document_date']??''),'notes'=>trim((string)($in['notes']??'')),'actor'=>trim((string)($in['actor']??'')),'document_id'=>$this->nullString($in['document_id']??'')]];return $this->rows($this->db->rest('POST','rpc/livira_relocate_inventory_load',[],$payload));}
    public function timeline(string $inventoryId):array{$events=$this->rows($this->db->rest('GET','events',['select'=>'*','inventory_id'=>'eq.'.$inventoryId,'order'=>'created_at.asc','limit'=>'5000']));foreach($events as &$e)if(!empty($e['document_id']))$e['attachments'][]=['id'=>$e['document_id'],'download_url'=>'/documents/'.$e['document_id'].'/download'];return $events;}
    public function processTimeline(string $id):array{return $this->rows($this->db->rest('GET','events',['select'=>'*','disposition_id'=>'eq.'.$id,'order'=>'created_at.asc','limit'=>'1000']));}
    public function listEvents(int $limit=50000):array{return $this->rows($this->db->rest('GET','events',['select'=>'*','order'=>'created_at.asc','limit'=>(string)$limit]));}

    public function dispositionQuery(array $f):array
    {
        $q=['select'=>'*'];if(!empty($f['inventory_id']))$q['inventory_id']='eq.'.$f['inventory_id'];if(!empty($f['type']))$q['disposition_type']='eq.'.$f['type'];if(!empty($f['facility_id']))$q['inventory_facility_id']='eq.'.$f['facility_id'];$allowed=$f['allowed_types']??[];if($allowed)$q['inventory_type']='in.('.implode(',',$allowed).')';if(!empty($f['status']))$q['status_code']='eq.'.$f['status'];if(!empty($f['include_status_codes']))$q['status_code']='in.('.implode(',',$f['include_status_codes']).')';if(!empty($f['exclude_status_codes']))$q['status_code']='not.in.('.implode(',',$f['exclude_status_codes']).')';if(!empty($f['only_inactive_inventory']))$q['inventory_is_active']='eq.false';elseif(empty($f['include_inactive_inventory']))$q['inventory_is_active']='eq.true';if(trim((string)($f['query']??''))!=='')$q['inventory_search_text']='ilike.*'.trim((string)$f['query']).'*';$q['order']=match($f['sort']??'newest'){'oldest'=>'updated_at.asc','value_desc'=>'inventory_goods_value.desc','value_asc'=>'inventory_goods_value.asc',default=>'updated_at.desc'};if((int)($f['limit']??0)>0)$q['limit']=(string)(int)$f['limit'];if((int)($f['offset']??0)>0)$q['offset']=(string)(int)$f['offset'];return $q;
    }
    public function listDispositions(array $f=[]):array{return $this->rows($this->db->rest('GET','disposition_details',$this->dispositionQuery($f)));}
    public function countDispositions(array $f=[]):int{$q=$this->dispositionQuery($f);unset($q['order'],$q['limit'],$q['offset']);return $this->db->restCount('disposition_details',$q);}
    public function processDashboard(string $type,int $year,array $allowed):array{return (array)$this->db->rest('POST','rpc/livira_process_dashboard',[],['p_type'=>$type,'p_year'=>$year,'p_types'=>$allowed]);}
    public function getDisposition(string $id):array{return $this->first($this->db->rest('GET','disposition_details',['select'=>'*','id'=>'eq.'.$id,'limit'=>'1']));}
    public function createDisposition(string $inventoryId,string $type,string $actor,string $notes=''):array{$item=$this->getInventory($inventoryId);return (array)$this->db->rest('POST','rpc/livira_create_disposition',[],['p_inventory_id'=>$inventoryId,'p_disposition_type'=>$type,'p_actor'=>$actor,'p_notes'=>$notes,'p_expected_updated_at'=>$item['updated_at']??null]);}
    public function addDispositionEvent(string $id,array $in):array
    {
        $p=$this->getDisposition($id);$code=trim((string)($in['code']??''));$actions=[];foreach(Domain::actionsFor((string)($p['disposition_type']??'')) as $a)$actions[$a['Code']]=$a;if(!isset($actions[$code]))throw new ApiException('Tahapan proses tidak valid.',422);$label=$actions[$code]['Label'];$status=$code;$round=(int)($p['round']??1);if($code==='lelang_penyesuaian'){$round++;$label='Lelang penyesuaian putaran '.$round;}if($code==='selesai_lelang'){$status=(string)($in['auction_outcome']??'');$label=$status==='laku'?'Laku':'Tidak laku';}if($code==='ba_serah_terima')$label='BA Serah Terima '.strtoupper((string)($in['transfer_type']??''));$processPatch=['round'=>$round,'status_code'=>$status,'status_label'=>$label];
        if($code==='selesai_lelang')$processPatch+=['sale_value'=>(int)($in['sale_value']??0),'auction_outcome'=>$status];if($code==='kep_htl')$processPatch['htl_value']=(int)($in['htl_value']??0);if($code==='jadwal_lelang')$processPatch+=['execution_start_date'=>$this->nullableDate($in['execution_start_date']??''),'execution_end_date'=>$this->nullableDate($in['execution_end_date']??''),'schedule_document_no'=>trim((string)($in['document_no']??'')),'schedule_document_date'=>$this->nullableDate($in['document_date']??'')];if($code==='alokasi_hasil_lelang')$processPatch['allocation_target']=trim((string)($in['allocation_target']??''));if(in_array($code,['kep_musnah','ba_musnah'],true))$processPatch['destruction_cost']=(int)($in['destruction_cost']??0);if($code==='ba_serah_terima')$processPatch['transfer_type']=trim((string)($in['transfer_type']??''));foreach(['recipient_code','recipient_name'] as $k)if(!empty($in[$k]))$processPatch[$k]=$in[$k];$itemPatch=['status_code'=>$status,'status_label'=>$label];if(in_array($code,['alokasi_hasil_lelang','ba_musnah','ba_serah_terima'],true)){$processPatch['is_active']=false;$itemPatch['current_disposition']=null;}
        $event=['code'=>$code,'label'=>$label,'document_no'=>trim((string)($in['document_no']??'')),'document_date'=>$this->nullableDate($in['document_date']??''),'notes'=>trim((string)($in['notes']??'')),'actor'=>trim((string)($in['actor']??'')),'document_id'=>$this->nullString($in['document_id']??'')];return (array)$this->db->rest('POST','rpc/livira_apply_disposition_event',[],['p_disposition_id'=>$id,'p_expected_updated_at'=>$p['updated_at']??null,'p_process_patch'=>$processPatch,'p_item_patch'=>$itemPatch,'p_event'=>$event]);
    }

    public function createUserApplication(string $authId,string $name,string $email):array{$existing=$this->rows($this->db->rest('GET','app_users',['select'=>'*','auth_user_id'=>'eq.'.$authId,'limit'=>'1']));if($existing)return $this->first($this->db->rest('PATCH','app_users',['id'=>'eq.'.$existing[0]['id'],'select'=>'*'],['name'=>trim($name),'email'=>strtolower(trim($email)),'updated_at'=>$this->now()]));return $this->first($this->db->rest('POST','app_users',['select'=>'*'],['auth_user_id'=>$authId,'name'=>trim($name),'email'=>strtolower(trim($email)),'approval_status'=>'pending']));}
    public function markUserEmailVerified(string $authId,string $email):void{$q=$authId!==''?['auth_user_id'=>'eq.'.$authId]:['email'=>'eq.'.strtolower(trim($email))];$this->db->rest('PATCH','app_users',$q,['email_verified'=>true,'email_verified_at'=>$this->now(),'updated_at'=>$this->now()]);}
    public function userByAuthId(string $authId):array{$u=$this->first($this->db->rest('GET','app_user_access',['select'=>'*','auth_user_id'=>'eq.'.$authId,'limit'=>'1']));$u['permissions']=Domain::normalizePermissions($u['permissions']??[]);return $u;}
    public function listUsers():array{$u=$this->rows($this->db->rest('GET','app_user_access',['select'=>'*','order'=>'created_at.desc','limit'=>'1000']));foreach($u as &$x)$x['permissions']=Domain::normalizePermissions($x['permissions']??[]);return $u;}
    public function approveUser(string $id,string $roleId,string $actor):void{$role=$this->rows($this->db->rest('GET','app_roles',['select'=>'id','id'=>'eq.'.$roleId,'active'=>'eq.true','limit'=>'1']));$user=$this->first($this->db->rest('GET','app_users',['select'=>'id,email_verified','id'=>'eq.'.$id,'limit'=>'1']));if(!$role||empty($user['email_verified']))throw new ApiException('Email belum terverifikasi atau role tidak aktif.',422);$this->db->rest('PATCH','app_users',['id'=>'eq.'.$id],['approval_status'=>'approved','role_id'=>$roleId,'rejection_reason'=>'','approved_by'=>$actor,'approved_at'=>$this->now(),'updated_at'=>$this->now()]);}
    public function rejectUser(string $id,string $reason,string $actor):void{$this->db->rest('PATCH','app_users',['id'=>'eq.'.$id],['approval_status'=>'rejected','role_id'=>null,'rejection_reason'=>trim($reason),'approved_by'=>$actor,'approved_at'=>$this->now(),'updated_at'=>$this->now()]);}
    public function updateUserRole(string $id,string $roleId,string $actor):void{$this->db->rest('PATCH','app_users',['id'=>'eq.'.$id,'approval_status'=>'eq.approved'],['role_id'=>$roleId,'approved_by'=>$actor,'updated_at'=>$this->now()]);}
    public function deleteUser(string $id):array{$u=$this->first($this->db->rest('GET','app_users',['select'=>'*','id'=>'eq.'.$id,'limit'=>'1']));$this->db->auth('DELETE','admin/users/'.rawurlencode((string)$u['auth_user_id']));return $u;}
    public function listRoles(bool $includeInactive=true):array{$q=['select'=>'*','order'=>'name.asc','limit'=>'1000'];if(!$includeInactive)$q['active']='eq.true';$roles=$this->rows($this->db->rest('GET','app_roles',$q));$assign=$this->rows($this->db->rest('GET','app_users',['select'=>'role_id','role_id'=>'not.is.null','limit'=>'10000']));$counts=[];foreach($assign as $a)$counts[$a['role_id']]=($counts[$a['role_id']]??0)+1;foreach($roles as &$r){$r['permissions']=Domain::normalizePermissions($r['permissions']??[]);$r['assigned_users']=$counts[$r['id']]??0;}return $roles;}
    public function createRole(array $in):array{$permissions=Domain::normalizePermissions($in['permissions']??[]);if(trim((string)($in['name']??''))===''||!$permissions)throw new ApiException('Nama role dan minimal satu akses wajib diisi.',422);return $this->first($this->db->rest('POST','app_roles',['select'=>'*'],['name'=>trim((string)$in['name']),'description'=>trim((string)($in['description']??'')),'permissions'=>$permissions,'active'=>true,'created_by'=>$in['actor']??'']));}
    public function updateRole(string $id,array $in):array{$permissions=Domain::normalizePermissions($in['permissions']??[]);return $this->first($this->db->rest('PATCH','app_roles',['id'=>'eq.'.$id,'select'=>'*'],['name'=>trim((string)$in['name']),'description'=>trim((string)($in['description']??'')),'permissions'=>$permissions,'updated_at'=>$this->now()]));}
    public function setRoleActive(string $id,bool $active):void{$this->db->rest('PATCH','app_roles',['id'=>'eq.'.$id],['active'=>$active,'updated_at'=>$this->now()]);}
    public function deleteRole(string $id):array{return $this->first($this->db->rest('DELETE','app_roles',['id'=>'eq.'.$id,'select'=>'*']));}

    public function parameterOptions(string $group='',bool $includeInactive=true):array{$out=[];if($group===''||$group!=='tpp'){$q=['select'=>'*','order'=>'group_code.asc,sort_order.asc,label.asc','limit'=>'2000'];if($group!=='')$q['group_code']='eq.'.$group;if(!$includeInactive)$q['active']='eq.true';$out=$this->rows($this->db->rest('GET','app_parameters',$q));}if($group===''||$group==='tpp')foreach($this->facilities($includeInactive) as $f)$out[]=['id'=>'facility--'.$f['id'],'group_code'=>'tpp','code'=>$f['id'],'label'=>$f['name'],'active'=>$f['active'],'system'=>true,'sort_order'=>$f['sort_order'],'created_at'=>$f['created_at']??null];return $out;}
    public function createParameter(array $in):array{$group=trim((string)($in['group_code']??''));$label=trim((string)($in['label']??''));$code=$this->slug((string)($in['code']??$label));$sort=max(1,(int)($in['sort_order']??999));$applies=$this->normalizeApplies($group,(array)($in['applies_to']??[]));if($group==='tpp')return $this->first($this->db->rest('POST','facilities',['select'=>'*'],['id'=>$code,'name'=>$label,'active'=>true,'sort_order'=>$sort,'yard_capacity'=>0,'yard_used'=>0,'shed_capacity'=>0,'shed_used'=>0]));return $this->first($this->db->rest('POST','app_parameters',['select'=>'*'],['group_code'=>$group,'code'=>$code,'label'=>$label,'applies_to'=>$applies,'sort_order'=>$sort,'active'=>true,'created_by'=>$in['actor']??'']));}
    public function updateParameter(string $id,array $in):array{$label=trim((string)($in['label']??''));$sort=max(1,(int)($in['sort_order']??999));if(str_starts_with($id,'facility--')){$fid=substr($id,10);$r=(array)$this->db->rest('POST','rpc/livira_update_facility_parameter',[],['p_facility_id'=>$fid,'p_name'=>$label,'p_sort_order'=>$sort]);return ['id'=>$id,'group_code'=>'tpp','code'=>$r['id']??$fid,'label'=>$r['name']??$label,'active'=>$r['active']??true,'system'=>true,'sort_order'=>$r['sort_order']??$sort];}$ex=$this->first($this->db->rest('GET','app_parameters',['select'=>'*','id'=>'eq.'.$id,'limit'=>'1']));return $this->first($this->db->rest('PATCH','app_parameters',['id'=>'eq.'.$id,'select'=>'*'],['label'=>$label,'applies_to'=>$this->normalizeApplies((string)$ex['group_code'],(array)($in['applies_to']??[])),'sort_order'=>$sort,'updated_at'=>$this->now()]));}
    public function setParameterActive(string $id,bool $active):void{if(str_starts_with($id,'facility--')){$this->db->rest('PATCH','facilities',['id'=>'eq.'.substr($id,10)],['active'=>$active]);}else$this->db->rest('PATCH','app_parameters',['id'=>'eq.'.$id],['active'=>$active,'updated_at'=>$this->now()]);}

    public function createDocument(array $file,string $actor):array{$name=basename((string)$file['name']);$tmp=(string)$file['tmp_name'];$size=(int)$file['size'];if($size<=0||$size>8*1024*1024||!is_uploaded_file($tmp)&&!is_file($tmp))throw new ApiException('Dokumen tidak valid atau melebihi 8 MB.',422);$content=(string)file_get_contents($tmp);$mime=(new \finfo(FILEINFO_MIME_TYPE))->buffer($content);$allowed=['application/pdf','image/jpeg','image/png','image/webp','image/gif'];if(!in_array($mime,$allowed,true))throw new ApiException('Format dokumen harus PDF atau gambar.',422);$sha=hash('sha256',$content);$path=gmdate('Y/m/d').'/'.bin2hex(random_bytes(16)).(['application/pdf'=>'.pdf','image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp','image/gif'=>'.gif'][$mime]??'');$this->db->storage('POST',$this->config->storageBucket,$path,$mime,$content);try{return $this->first($this->db->rest('POST','uploaded_documents',['select'=>'id,file_name,mime_type,size_bytes,uploaded_by,storage_bucket,storage_path,sha256,created_at'],['file_name'=>$name,'mime_type'=>$mime,'size_bytes'=>$size,'sha256'=>$sha,'uploaded_by'=>$actor,'storage_bucket'=>$this->config->storageBucket,'storage_path'=>$path]));}catch(\Throwable $e){try{$this->db->storage('DELETE',$this->config->storageBucket,$path);}catch(\Throwable){}throw $e;}}
    public function getDocument(string $id):array{$row=$this->first($this->db->rest('GET','uploaded_documents',['select'=>'*','id'=>'eq.'.$id,'limit'=>'1']));$content=!empty($row['storage_path'])?$this->db->storage('GET',(string)$row['storage_bucket'],(string)$row['storage_path']):base64_decode((string)($row['content_base64']??''),true);if(!is_string($content)||strlen($content)!==(int)$row['size_bytes']||(!empty($row['sha256'])&&!hash_equals(strtolower((string)$row['sha256']),hash('sha256',$content))))throw new ApiException('Integritas dokumen tidak sesuai.',500);return [$row,$content];}
    public function documentAccess(string $id):array{$links=$this->rows($this->db->rest('GET','events',['select'=>'inventory_id,disposition_type,code','document_id'=>'eq.'.$id,'limit'=>'100']));if(!$links)throw new ApiException('Dokumen tidak ditemukan.',404);$ids=array_values(array_unique(array_filter(array_column($links,'inventory_id'))));$items=$ids?$this->rows($this->db->rest('GET','inventory_items',['select'=>'*','id'=>'in.('.implode(',',$ids).')'])):[];$by=[];foreach($items as $i)$by[$i['id']]=$i;$out=[];foreach($links as $l)if(isset($by[$l['inventory_id']]))$out[]=['inventory'=>$by[$l['inventory_id']],'disposition_type'=>$l['disposition_type']??'','event_code'=>$l['code']??''];return $out;}
    public function notifications(array $allowed):array{return (array)$this->db->rest('POST','rpc/livira_notification_summary',[],['p_types'=>$allowed]);}
    public function audit(array $e):void{try{$this->db->rest('POST','audit_logs',[],['actor_subject'=>$e['actor_subject']??'','actor_name'=>$e['actor_name']??'','action'=>$e['action']??'','entity_type'=>$e['entity_type']??'','entity_id'=>$e['entity_id']??'','outcome'=>$e['outcome']??'','ip_address'=>$e['ip_address']??'','user_agent'=>$e['user_agent']??'','request_id'=>$e['request_id']??'','metadata'=>$e['metadata']??new \stdClass()]);}catch(\Throwable) {}}
    public function listReconciliations(int $limit=5000):array{return $this->rows($this->db->rest('GET','reconciliations',['select'=>'*','order'=>'created_at.desc','limit'=>(string)$limit]));}
    public function listCorrections(int $limit=5000):array{return $this->rows($this->db->rest('GET','reconciliations',['select'=>'*','reconciliation_type'=>'eq.data_correction','order'=>'created_at.desc','limit'=>(string)$limit]));}
    public function reconcile(array $in):array{$type=trim((string)($in['type']??''));if($type==='found_not_recorded'){$new=$in['new_item']??[];$new['reconciliation_created']=true;$new['actor']=$in['actor'];$new['document_id']=$in['document_id']??'';$item=$this->createInventory($new);$record=$this->first($this->db->rest('POST','reconciliations',['select'=>'*'],['reconciliation_type'=>$type,'action'=>'added','inventory_id'=>$item['id'],'inventory_reference'=>$item['reference_no'],'inventory_type'=>$item['item_type'],'result_status_code'=>$item['status_code'],'result_status_label'=>$item['status_label'],'notes'=>$in['notes'],'actor'=>$in['actor']]));return [$record,$item];}$item=$this->getInventory((string)$in['inventory_id']);$updated=$this->first($this->db->rest('PATCH','inventory_items',['id'=>'eq.'.$item['id'],'select'=>'*'],['is_active'=>false,'current_disposition'=>null,'status_code'=>'rekonsiliasi_tidak_ditemukan','status_label'=>'Tidak ditemukan di lapangan','location_status'=>'Tidak ditemukan saat rekonsiliasi','updated_at'=>$this->now()]));$this->db->rest('PATCH','dispositions',['inventory_id'=>'eq.'.$item['id'],'is_active'=>'eq.true'],['is_active'=>false,'updated_at'=>$this->now()]);$this->db->rest('POST','events',[],['inventory_id'=>$item['id'],'code'=>$updated['status_code'],'label'=>$updated['status_label'],'notes'=>$in['notes'],'actor'=>$in['actor'],'created_at'=>$this->now(),'document_id'=>$this->nullString($in['document_id']??'')]);$record=$this->first($this->db->rest('POST','reconciliations',['select'=>'*'],['reconciliation_type'=>$type,'action'=>'removed','inventory_id'=>$item['id'],'inventory_reference'=>$item['reference_no'],'inventory_type'=>$item['item_type'],'previous_status_code'=>$item['status_code'],'previous_status_label'=>$item['status_label'],'result_status_code'=>$updated['status_code'],'result_status_label'=>$updated['status_label'],'notes'=>$in['notes'],'actor'=>$in['actor']]));return [$record,$updated];}
    public function correctInventory(array $payload):array{return (array)$this->db->rest('POST','rpc/livira_correct_inventory_data',[],$payload);}

    private function date(mixed $v):?string{if(!is_string($v)||trim($v)==='')return null;$t=strtotime($v);return $t===false?null:date('Y-m-d',$t);}
    private function nullableDate(mixed $v):?string{$d=$this->date($v);return $d===null?null:$d;}
    private function bool(mixed $v):bool{return filter_var($v,FILTER_VALIDATE_BOOL)||in_array(strtolower((string)$v),['1','ya','yes','on'],true);}
    private function nullString(mixed $v):?string{$s=trim((string)$v);return $s===''?null:$s;}
    private function normalizeContainer(string $v,bool $formatted=true):string{$c=strtoupper(preg_replace('/[\s\-\.]+/','',trim($v)));if($c==='')return'';if(!preg_match('/^[A-Z]{4}[0-9]{7}$/',$c))throw new ApiException('Nomor kontainer harus 4 huruf dan 7 angka, contoh ABCD1234567.',422);return $formatted?substr($c,0,4).' '.substr($c,4,6).'-'.substr($c,10):$c;}
    private function slug(string $v):string{$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','_',$v);return trim((string)$v,'_');}
    private function normalizeApplies(string $group,array $values):string{$types=array_values(array_intersect(array_map('strtoupper',$values),Domain::TYPES));return in_array($group,['exit_type','transfer_type','load_type'],true)?implode(',',$types):'';}
}
